DEBUG [2021-06-29 11:07:07] [b38ec8d3bc034a19b0d3053f626d3c71] backend.apps.whitelist /Users/jamesge/GitHubProjects/bk-bcs-saas/bcs-app/backend/apps/whitelist.py 47 <module> 62511 4566232576 
 	 Load extension failed: No module named 'backend.apps.whitelist_ext' 

DEBUG [2021-06-29 11:07:07] [76be083f9df54b9d9fa5141b7e715dc7] backend.apps.constants /Users/jamesge/GitHubProjects/bk-bcs-saas/bcs-app/backend/apps/constants.py 148 <module> 62511 4566232576 
 	 Load extension failed: No module named 'backend.apps.constants_ext' 

DEBUG [2021-06-29 11:07:07] [96849223183946a08b32e07b63b6ee83] backend.components.paas_cc /Users/jamesge/GitHubProjects/bk-bcs-saas/bcs-app/backend/components/paas_cc.py 587 <module> 62511 4566232576 
 	 Load extension failed: No module named 'backend.components.paas_cc_ext' 

DEBUG [2021-06-29 11:07:08] [03534153ecdf4822bcf61c36624f52b5] backend.bcs_k8s.helm.constants /Users/jamesge/GitHubProjects/bk-bcs-saas/bcs-app/backend/bcs_k8s/helm/constants.py 60 <module> 62511 4566232576 
 	 Load extension failed: No module named 'backend.bcs_k8s.helm.constants_ext' 

DEBUG [2021-06-29 11:07:08] [186769af6af645f198d6e3438da28ec7] backend.bcs_k8s.helm.utils.repo_bk /Users/jamesge/GitHubProjects/bk-bcs-saas/bcs-app/backend/bcs_k8s/helm/utils/repo_bk.py 72 <module> 62511 4566232576 
 	 Load extension failed: No module named 'backend.bcs_k8s.helm.utils.repo_ext' 

DEBUG [2021-06-29 11:07:08] [2fabe1dd2bb74675be0ebfbf5d7690e6] backend.accounts.bcs_perm /Users/jamesge/GitHubProjects/bk-bcs-saas/bcs-app/backend/accounts/bcs_perm/__init__.py 266 <module> 62511 4566232576 
 	 Load extension failed: No module named 'backend.accounts.bcs_perm.perm_ext' 

DEBUG [2021-06-29 11:07:08] [ea06bca42d584c6eabce42a8f72b773e] backend.accounts.bcs_perm.tasks /Users/jamesge/GitHubProjects/bk-bcs-saas/bcs-app/backend/accounts/bcs_perm/tasks.py 27 <module> 62511 4566232576 
 	 Load extension failed: No module named 'backend.accounts.bcs_perm.tasks_ext' 

DEBUG [2021-06-29 11:07:08] [aa2cb34cb09a458e9ed5e36b14d294b7] backend.components.ops /Users/jamesge/GitHubProjects/bk-bcs-saas/bcs-app/backend/components/ops.py 186 <module> 62511 4566232576 
 	 Load ops_ext failed, No module named 'backend.components.ops_ext' 

DEBUG [2021-06-29 11:07:08] [9c1ac45505e4461da1a4bb4563c35157] backend.components.paas_auth /Users/jamesge/GitHubProjects/bk-bcs-saas/bcs-app/backend/components/paas_auth.py 50 <module> 62511 4566232576 
 	 Load extension failed: No module named 'backend.components.paas_auth_ext' 

DEBUG [2021-06-29 11:07:08] [b7bc6903cdeb4bbebf809511387248fe] backend.apps.cluster.tasks /Users/jamesge/GitHubProjects/bk-bcs-saas/bcs-app/backend/apps/cluster/tasks.py 242 <module> 62511 4566232576 
 	 Load extension failed: No module named 'backend.apps.cluster.tasks_ext' 

DEBUG [2021-06-29 11:07:08] [f705f1512e284befb86e2d2cf7dd5942] backend.components.ticket /Users/jamesge/GitHubProjects/bk-bcs-saas/bcs-app/backend/components/ticket.py 90 <module> 62511 4566232576 
 	 `patch_ticket_client` hook not found, will skip 

DEBUG [2021-06-29 11:07:08] [5f5d86c6baa141d8ba3032959f2753b1] backend.components.cc /Users/jamesge/GitHubProjects/bk-bcs-saas/bcs-app/backend/components/cc.py 337 <module> 62511 4566232576 
 	 Load extension failed: No module named 'backend.components.cc_ext' 

DEBUG [2021-06-29 11:07:22] [c5b47593289245a78f64b8d45675125d] backend.apps.whitelist /Users/jamesge/GitHubProjects/bk-bcs-saas/bcs-app/backend/apps/whitelist.py 47 <module> 62654 4619369984 
 	 Load extension failed: No module named 'backend.apps.whitelist_ext' 

DEBUG [2021-06-29 11:07:22] [dab297f33720408bb0521320507b1a7b] backend.apps.constants /Users/jamesge/GitHubProjects/bk-bcs-saas/bcs-app/backend/apps/constants.py 148 <module> 62654 4619369984 
 	 Load extension failed: No module named 'backend.apps.constants_ext' 

DEBUG [2021-06-29 11:07:22] [465e40567a4d4599b3f79611c6e733b7] backend.components.paas_cc /Users/jamesge/GitHubProjects/bk-bcs-saas/bcs-app/backend/components/paas_cc.py 587 <module> 62654 4619369984 
 	 Load extension failed: No module named 'backend.components.paas_cc_ext' 

DEBUG [2021-06-29 11:07:23] [f898a93a841b484e931d426adc20b43e] backend.bcs_k8s.helm.constants /Users/jamesge/GitHubProjects/bk-bcs-saas/bcs-app/backend/bcs_k8s/helm/constants.py 60 <module> 62654 4619369984 
 	 Load extension failed: No module named 'backend.bcs_k8s.helm.constants_ext' 

DEBUG [2021-06-29 11:07:23] [fadf4b0b9a2d42a3b63abe59db5195e8] backend.bcs_k8s.helm.utils.repo_bk /Users/jamesge/GitHubProjects/bk-bcs-saas/bcs-app/backend/bcs_k8s/helm/utils/repo_bk.py 72 <module> 62654 4619369984 
 	 Load extension failed: No module named 'backend.bcs_k8s.helm.utils.repo_ext' 

DEBUG [2021-06-29 11:07:23] [d21d37f843004a6197b4a82877c90231] backend.accounts.bcs_perm /Users/jamesge/GitHubProjects/bk-bcs-saas/bcs-app/backend/accounts/bcs_perm/__init__.py 266 <module> 62654 4619369984 
 	 Load extension failed: No module named 'backend.accounts.bcs_perm.perm_ext' 

DEBUG [2021-06-29 11:07:23] [5150d8a946294c988f017366aaaa8a9d] backend.accounts.bcs_perm.tasks /Users/jamesge/GitHubProjects/bk-bcs-saas/bcs-app/backend/accounts/bcs_perm/tasks.py 27 <module> 62654 4619369984 
 	 Load extension failed: No module named 'backend.accounts.bcs_perm.tasks_ext' 

DEBUG [2021-06-29 11:07:23] [9552ece3d4d54858845090a0a591b735] backend.components.ops /Users/jamesge/GitHubProjects/bk-bcs-saas/bcs-app/backend/components/ops.py 186 <module> 62654 4619369984 
 	 Load ops_ext failed, No module named 'backend.components.ops_ext' 

DEBUG [2021-06-29 11:07:23] [5aaaf6b1839f4f0784b5ddf3635544b6] backend.components.paas_auth /Users/jamesge/GitHubProjects/bk-bcs-saas/bcs-app/backend/components/paas_auth.py 50 <module> 62654 4619369984 
 	 Load extension failed: No module named 'backend.components.paas_auth_ext' 

DEBUG [2021-06-29 11:07:23] [d3ff3abe6e58446a987bbea925c6ab59] backend.apps.cluster.tasks /Users/jamesge/GitHubProjects/bk-bcs-saas/bcs-app/backend/apps/cluster/tasks.py 242 <module> 62654 4619369984 
 	 Load extension failed: No module named 'backend.apps.cluster.tasks_ext' 

DEBUG [2021-06-29 11:07:23] [c9c456e1fe704272949132edbfbde3e5] backend.components.ticket /Users/jamesge/GitHubProjects/bk-bcs-saas/bcs-app/backend/components/ticket.py 90 <module> 62654 4619369984 
 	 `patch_ticket_client` hook not found, will skip 

DEBUG [2021-06-29 11:07:23] [f7a9c357eb8f42f5b5037d072b8c3a27] backend.components.cc /Users/jamesge/GitHubProjects/bk-bcs-saas/bcs-app/backend/components/cc.py 337 <module> 62654 4619369984 
 	 Load extension failed: No module named 'backend.components.cc_ext' 

DEBUG [2021-06-29 11:07:49] [4809b28024184a4fb38e35e89d99003a] backend.apps.whitelist /Users/jamesge/GitHubProjects/bk-bcs-saas/bcs-app/backend/apps/whitelist.py 47 <module> 62844 4648758784 
 	 Load extension failed: No module named 'backend.apps.whitelist_ext' 

DEBUG [2021-06-29 11:07:49] [170f745df7f44bd3931d9db400a67c32] backend.apps.constants /Users/jamesge/GitHubProjects/bk-bcs-saas/bcs-app/backend/apps/constants.py 148 <module> 62844 4648758784 
 	 Load extension failed: No module named 'backend.apps.constants_ext' 

DEBUG [2021-06-29 11:07:49] [cd73f5cb55284af3a4b25aa47f829568] backend.components.paas_cc /Users/jamesge/GitHubProjects/bk-bcs-saas/bcs-app/backend/components/paas_cc.py 587 <module> 62844 4648758784 
 	 Load extension failed: No module named 'backend.components.paas_cc_ext' 

DEBUG [2021-06-29 11:07:49] [bf03408f388645c1be9b557571cc666b] backend.bcs_k8s.helm.constants /Users/jamesge/GitHubProjects/bk-bcs-saas/bcs-app/backend/bcs_k8s/helm/constants.py 60 <module> 62844 4648758784 
 	 Load extension failed: No module named 'backend.bcs_k8s.helm.constants_ext' 

DEBUG [2021-06-29 11:07:49] [5607cb75b74e47bab3a75721f4da64ca] backend.bcs_k8s.helm.utils.repo_bk /Users/jamesge/GitHubProjects/bk-bcs-saas/bcs-app/backend/bcs_k8s/helm/utils/repo_bk.py 72 <module> 62844 4648758784 
 	 Load extension failed: No module named 'backend.bcs_k8s.helm.utils.repo_ext' 

DEBUG [2021-06-29 11:07:49] [04ad620e8e2446a4ad15fc713d3558f0] backend.accounts.bcs_perm /Users/jamesge/GitHubProjects/bk-bcs-saas/bcs-app/backend/accounts/bcs_perm/__init__.py 266 <module> 62844 4648758784 
 	 Load extension failed: No module named 'backend.accounts.bcs_perm.perm_ext' 

DEBUG [2021-06-29 11:07:49] [8806be7cfb974520a919f291eaf5df13] backend.accounts.bcs_perm.tasks /Users/jamesge/GitHubProjects/bk-bcs-saas/bcs-app/backend/accounts/bcs_perm/tasks.py 27 <module> 62844 4648758784 
 	 Load extension failed: No module named 'backend.accounts.bcs_perm.tasks_ext' 

DEBUG [2021-06-29 11:07:49] [3f9d4c75b00b4e12b626194bd93b8894] backend.components.ops /Users/jamesge/GitHubProjects/bk-bcs-saas/bcs-app/backend/components/ops.py 186 <module> 62844 4648758784 
 	 Load ops_ext failed, No module named 'backend.components.ops_ext' 

DEBUG [2021-06-29 11:07:49] [c070c96f6b574b05a5b24898543f6c1e] backend.components.paas_auth /Users/jamesge/GitHubProjects/bk-bcs-saas/bcs-app/backend/components/paas_auth.py 50 <module> 62844 4648758784 
 	 Load extension failed: No module named 'backend.components.paas_auth_ext' 

DEBUG [2021-06-29 11:07:49] [6f09f9e617f845dd9fa6e200daec57e4] backend.apps.cluster.tasks /Users/jamesge/GitHubProjects/bk-bcs-saas/bcs-app/backend/apps/cluster/tasks.py 242 <module> 62844 4648758784 
 	 Load extension failed: No module named 'backend.apps.cluster.tasks_ext' 

DEBUG [2021-06-29 11:07:49] [a65956674e074e39a322ea474ca8f736] backend.components.ticket /Users/jamesge/GitHubProjects/bk-bcs-saas/bcs-app/backend/components/ticket.py 90 <module> 62844 4648758784 
 	 `patch_ticket_client` hook not found, will skip 

DEBUG [2021-06-29 11:07:49] [5db71d8e3e154860a6214f161ddc0344] backend.components.cc /Users/jamesge/GitHubProjects/bk-bcs-saas/bcs-app/backend/components/cc.py 337 <module> 62844 4648758784 
 	 Load extension failed: No module named 'backend.components.cc_ext' 

DEBUG [2021-06-29 11:07:50] [2534c0b8c38b4bdd90ffa2a462c099ed] backend.utils.authentication /Users/jamesge/GitHubProjects/bk-bcs-saas/bcs-app/backend/utils/authentication.py 172 <module> 62844 4648758784 
 	 Load extension failed: No module named 'backend.utils.authentication_ext' 

DEBUG [2021-06-29 11:07:50] [61da32de0b1e43afb44f5b31063f4d02] backend.apps.depot.api /Users/jamesge/GitHubProjects/bk-bcs-saas/bcs-app/backend/apps/depot/api.py 178 <module> 62844 4648758784 
 	 Load extension failed: No module named 'backend.apps.depot.api_ext' 

DEBUG [2021-06-29 11:07:50] [1d82142f348e4e448f49cb1879a2cfe6] backend.bcs_k8s.helm.providers.constants /Users/jamesge/GitHubProjects/bk-bcs-saas/bcs-app/backend/bcs_k8s/helm/providers/constants.py 28 <module> 62844 4648758784 
 	 Load extension for constants failed 

DEBUG [2021-06-29 11:07:50] [217171460fdf4b19bc6b04271dd37c1f] backend.apps.projects.utils /Users/jamesge/GitHubProjects/bk-bcs-saas/bcs-app/backend/apps/projects/utils.py 68 <module> 62844 4648758784 
 	 Load extension failed: No module named 'backend.apps.projects.utils_ext' 

DEBUG [2021-06-29 11:07:50] [24221bb46eb446baaa962831237cb748] backend.apps.projects.views /Users/jamesge/GitHubProjects/bk-bcs-saas/bcs-app/backend/apps/projects/views.py 314 <module> 62844 4648758784 
 	 Load extension failed: No module named 'backend.apps.projects.views_ext' 

DEBUG [2021-06-29 11:07:50] [74af9f7807884afa85f5c883c3784014] backend.components.data.constants /Users/jamesge/GitHubProjects/bk-bcs-saas/bcs-app/backend/components/data/constants.py 58 <module> 62844 4648758784 
 	 Load extension failed: No module named 'backend.components.data.constants_ext' 

DEBUG [2021-06-29 11:07:50] [e77b438cbe5642899b75653e7470e122] backend.components.data.databus /Users/jamesge/GitHubProjects/bk-bcs-saas/bcs-app/backend/components/data/databus.py 390 <module> 62844 4648758784 
 	 Load extension failed: No module named 'backend.components.data.databus_ext' 

DEBUG [2021-06-29 11:07:50] [2c5cbcbb48c8495483961afeb90a23b7] backend.components.gse /Users/jamesge/GitHubProjects/bk-bcs-saas/bcs-app/backend/components/gse.py 48 <module> 62844 4648758784 
 	 Load extension failed: No module named 'backend.components.gse_ext' 

DEBUG [2021-06-29 11:07:50] [1f51267c897545c8985afe5bf649a994] backend.web_console.constant_bk /Users/jamesge/GitHubProjects/bk-bcs-saas/bcs-app/backend/web_console/constant_bk.py 44 <module> 62844 4648758784 
 	 constant extension "constant_ext" module not found 

DEBUG [2021-06-29 11:07:50] [7142b5a5166d4f708a824b841cf03c34] backend.apps.network.ext_routes /Users/jamesge/GitHubProjects/bk-bcs-saas/bcs-app/backend/apps/network/ext_routes.py 30 <module> 62844 4648758784 
 	 Load extension failed: No module named 'backend.apps.network.ext_routes_ext' 

DEBUG [2021-06-29 11:07:50] [25b3ae6c23b749e8ae42194ea2135eed] backend.apps.network.utils /Users/jamesge/GitHubProjects/bk-bcs-saas/bcs-app/backend/apps/network/utils.py 339 <module> 62844 4648758784 
 	 Load extension failed: No module named 'backend.apps.network.utils_ext' 

DEBUG [2021-06-29 11:07:50] [acf8041f24a14a30b9e61f0eff687e97] backend.bcs_k8s.app.repo /Users/jamesge/GitHubProjects/bk-bcs-saas/bcs-app/backend/bcs_k8s/app/repo.py 48 <module> 62844 4648758784 
 	 Load extension failed: No module named 'backend.bcs_k8s.app.repo_ext' 

ERROR [2021-06-29 11:07:50] [258ddfc68e5749c28f2a7e5520392c53] backend.utils.requests /Users/jamesge/GitHubProjects/bk-bcs-saas/bcs-app/backend/utils/requests.py 61 _request 62844 4648758784 
 	 第三方请求异常，url: /apigw/managementapi/get_api_public_key/, Invalid URL '/apigw/managementapi/get_api_public_key/': No schema supplied. Perhaps you meant http:///apigw/managementapi/get_api_public_key/? 
Traceback (most recent call last):
  File "/Users/jamesge/GitHubProjects/bk-bcs-saas/bcs-app/backend/bcs_web/constants.py", line 25, in <module>
    BCS_APP_APIGW_PUBLIC_KEY = getattr(settings, 'BCS_APP_APIGW_PUBLIC_KEY')
  File "/Users/jamesge/.local/share/virtualenvs/paas-web-backend-ce-js1Hoyit/lib/python3.6/site-packages/django/conf/__init__.py", line 57, in __getattr__
    val = getattr(self._wrapped, name)
AttributeError: 'Settings' object has no attribute 'BCS_APP_APIGW_PUBLIC_KEY'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jamesge/GitHubProjects/bk-bcs-saas/bcs-app/backend/utils/requests.py", line 52, in _request
    resp = rpool.request(method, url, params=params, data=data, json=json, headers=headers, **kwargs)
  File "/Users/jamesge/.local/share/virtualenvs/paas-web-backend-ce-js1Hoyit/lib/python3.6/site-packages/requests/sessions.py", line 519, in request
    prep = self.prepare_request(req)
  File "/Users/jamesge/.local/share/virtualenvs/paas-web-backend-ce-js1Hoyit/lib/python3.6/site-packages/requests/sessions.py", line 462, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/Users/jamesge/.local/share/virtualenvs/paas-web-backend-ce-js1Hoyit/lib/python3.6/site-packages/requests/models.py", line 313, in prepare
    self.prepare_url(url, params)
  File "/Users/jamesge/.local/share/virtualenvs/paas-web-backend-ce-js1Hoyit/lib/python3.6/site-packages/requests/models.py", line 387, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '/apigw/managementapi/get_api_public_key/': No schema supplied. Perhaps you meant http:///apigw/managementapi/get_api_public_key/?
ERROR [2021-06-29 11:07:50] [0a33dc44abd242a381807d8ce77a4944] backend.components.apigw /Users/jamesge/GitHubProjects/bk-bcs-saas/bcs-app/backend/components/apigw.py 31 get_api_public_key 62844 4648758784 
 	 get api public key failed: 第三方请求失败，Invalid URL '/apigw/managementapi/get_api_public_key/': No schema supplied. Perhaps you meant http:///apigw/managementapi/get_api_public_key/? 
Traceback (most recent call last):
  File "/Users/jamesge/GitHubProjects/bk-bcs-saas/bcs-app/backend/bcs_web/constants.py", line 25, in <module>
    BCS_APP_APIGW_PUBLIC_KEY = getattr(settings, 'BCS_APP_APIGW_PUBLIC_KEY')
  File "/Users/jamesge/.local/share/virtualenvs/paas-web-backend-ce-js1Hoyit/lib/python3.6/site-packages/django/conf/__init__.py", line 57, in __getattr__
    val = getattr(self._wrapped, name)
AttributeError: 'Settings' object has no attribute 'BCS_APP_APIGW_PUBLIC_KEY'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jamesge/GitHubProjects/bk-bcs-saas/bcs-app/backend/utils/requests.py", line 52, in _request
    resp = rpool.request(method, url, params=params, data=data, json=json, headers=headers, **kwargs)
  File "/Users/jamesge/.local/share/virtualenvs/paas-web-backend-ce-js1Hoyit/lib/python3.6/site-packages/requests/sessions.py", line 519, in request
    prep = self.prepare_request(req)
  File "/Users/jamesge/.local/share/virtualenvs/paas-web-backend-ce-js1Hoyit/lib/python3.6/site-packages/requests/sessions.py", line 462, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/Users/jamesge/.local/share/virtualenvs/paas-web-backend-ce-js1Hoyit/lib/python3.6/site-packages/requests/models.py", line 313, in prepare
    self.prepare_url(url, params)
  File "/Users/jamesge/.local/share/virtualenvs/paas-web-backend-ce-js1Hoyit/lib/python3.6/site-packages/requests/models.py", line 387, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '/apigw/managementapi/get_api_public_key/': No schema supplied. Perhaps you meant http:///apigw/managementapi/get_api_public_key/?

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jamesge/GitHubProjects/bk-bcs-saas/bcs-app/backend/components/apigw.py", line 28, in get_api_public_key
    data = requests.bk_get(url, params=params, headers=headers)
  File "/Users/jamesge/GitHubProjects/bk-bcs-saas/bcs-app/backend/utils/decorators.py", line 116, in _wrapped_func
    resp = func(*args, **kwargs)
  File "/Users/jamesge/GitHubProjects/bk-bcs-saas/bcs-app/backend/utils/requests.py", line 62, in _request
    raise ComponentError(err_msg or error)
backend.utils.exceptions.ComponentError: 第三方请求失败，Invalid URL '/apigw/managementapi/get_api_public_key/': No schema supplied. Perhaps you meant http:///apigw/managementapi/get_api_public_key/?
DEBUG [2021-06-29 11:07:51] [1e8ebe5ef1c44c6cba5a5970aee6c433] backend.components.bk_repo /Users/jamesge/GitHubProjects/bk-bcs-saas/bcs-app/backend/components/bk_repo.py 68 <module> 62844 4648758784 
 	 Load extension failed: No module named 'backend.components.bk_repo_ext' 

ERROR [2021-06-29 11:07:51] [bf4f5e34a5084af19a4a149b937d3332] backend.utils.requests /Users/jamesge/GitHubProjects/bk-bcs-saas/bcs-app/backend/utils/requests.py 61 _request 62844 4648758784 
 	 第三方请求异常，url: /apigw/managementapi/get_api_public_key/, Invalid URL '/apigw/managementapi/get_api_public_key/': No schema supplied. Perhaps you meant http:///apigw/managementapi/get_api_public_key/? 
Traceback (most recent call last):
  File "/Users/jamesge/GitHubProjects/bk-bcs-saas/bcs-app/backend/utils/requests.py", line 52, in _request
    resp = rpool.request(method, url, params=params, data=data, json=json, headers=headers, **kwargs)
  File "/Users/jamesge/.local/share/virtualenvs/paas-web-backend-ce-js1Hoyit/lib/python3.6/site-packages/requests/sessions.py", line 519, in request
    prep = self.prepare_request(req)
  File "/Users/jamesge/.local/share/virtualenvs/paas-web-backend-ce-js1Hoyit/lib/python3.6/site-packages/requests/sessions.py", line 462, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/Users/jamesge/.local/share/virtualenvs/paas-web-backend-ce-js1Hoyit/lib/python3.6/site-packages/requests/models.py", line 313, in prepare
    self.prepare_url(url, params)
  File "/Users/jamesge/.local/share/virtualenvs/paas-web-backend-ce-js1Hoyit/lib/python3.6/site-packages/requests/models.py", line 387, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '/apigw/managementapi/get_api_public_key/': No schema supplied. Perhaps you meant http:///apigw/managementapi/get_api_public_key/?
ERROR [2021-06-29 11:07:51] [f6329f8f000a4401a1d18441c95edf8d] backend.components.apigw /Users/jamesge/GitHubProjects/bk-bcs-saas/bcs-app/backend/components/apigw.py 31 get_api_public_key 62844 4648758784 
 	 get api public key failed: 第三方请求失败，Invalid URL '/apigw/managementapi/get_api_public_key/': No schema supplied. Perhaps you meant http:///apigw/managementapi/get_api_public_key/? 
Traceback (most recent call last):
  File "/Users/jamesge/GitHubProjects/bk-bcs-saas/bcs-app/backend/utils/requests.py", line 52, in _request
    resp = rpool.request(method, url, params=params, data=data, json=json, headers=headers, **kwargs)
  File "/Users/jamesge/.local/share/virtualenvs/paas-web-backend-ce-js1Hoyit/lib/python3.6/site-packages/requests/sessions.py", line 519, in request
    prep = self.prepare_request(req)
  File "/Users/jamesge/.local/share/virtualenvs/paas-web-backend-ce-js1Hoyit/lib/python3.6/site-packages/requests/sessions.py", line 462, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/Users/jamesge/.local/share/virtualenvs/paas-web-backend-ce-js1Hoyit/lib/python3.6/site-packages/requests/models.py", line 313, in prepare
    self.prepare_url(url, params)
  File "/Users/jamesge/.local/share/virtualenvs/paas-web-backend-ce-js1Hoyit/lib/python3.6/site-packages/requests/models.py", line 387, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '/apigw/managementapi/get_api_public_key/': No schema supplied. Perhaps you meant http:///apigw/managementapi/get_api_public_key/?

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jamesge/GitHubProjects/bk-bcs-saas/bcs-app/backend/components/apigw.py", line 28, in get_api_public_key
    data = requests.bk_get(url, params=params, headers=headers)
  File "/Users/jamesge/GitHubProjects/bk-bcs-saas/bcs-app/backend/utils/decorators.py", line 116, in _wrapped_func
    resp = func(*args, **kwargs)
  File "/Users/jamesge/GitHubProjects/bk-bcs-saas/bcs-app/backend/utils/requests.py", line 62, in _request
    raise ComponentError(err_msg or error)
backend.utils.exceptions.ComponentError: 第三方请求失败，Invalid URL '/apigw/managementapi/get_api_public_key/': No schema supplied. Perhaps you meant http:///apigw/managementapi/get_api_public_key/?
DEBUG [2021-06-29 11:07:51] [3d96a4281dc241fca2cc74dc6d938aa7] backend.apps.apis.constants /Users/jamesge/GitHubProjects/bk-bcs-saas/bcs-app/backend/apps/apis/constants.py 40 <module> 62844 4648758784 
 	 Load extension failed: No module named 'backend.apps.apis.constants_ext' 

ERROR [2021-06-29 11:07:51] [01a204b7c38b4f248ffd61bf09100098] backend.utils.requests /Users/jamesge/GitHubProjects/bk-bcs-saas/bcs-app/backend/utils/requests.py 61 _request 62844 4648758784 
 	 第三方请求异常，url: /apigw/managementapi/get_api_public_key/, Invalid URL '/apigw/managementapi/get_api_public_key/': No schema supplied. Perhaps you meant http:///apigw/managementapi/get_api_public_key/? 
Traceback (most recent call last):
  File "/Users/jamesge/GitHubProjects/bk-bcs-saas/bcs-app/backend/apis/constants.py", line 25, in <module>
    BCS_APP_APIGW_PUBLIC_KEY = getattr(settings, 'BCS_APP_APIGW_PUBLIC_KEY')
  File "/Users/jamesge/.local/share/virtualenvs/paas-web-backend-ce-js1Hoyit/lib/python3.6/site-packages/django/conf/__init__.py", line 57, in __getattr__
    val = getattr(self._wrapped, name)
AttributeError: 'Settings' object has no attribute 'BCS_APP_APIGW_PUBLIC_KEY'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jamesge/GitHubProjects/bk-bcs-saas/bcs-app/backend/utils/requests.py", line 52, in _request
    resp = rpool.request(method, url, params=params, data=data, json=json, headers=headers, **kwargs)
  File "/Users/jamesge/.local/share/virtualenvs/paas-web-backend-ce-js1Hoyit/lib/python3.6/site-packages/requests/sessions.py", line 519, in request
    prep = self.prepare_request(req)
  File "/Users/jamesge/.local/share/virtualenvs/paas-web-backend-ce-js1Hoyit/lib/python3.6/site-packages/requests/sessions.py", line 462, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/Users/jamesge/.local/share/virtualenvs/paas-web-backend-ce-js1Hoyit/lib/python3.6/site-packages/requests/models.py", line 313, in prepare
    self.prepare_url(url, params)
  File "/Users/jamesge/.local/share/virtualenvs/paas-web-backend-ce-js1Hoyit/lib/python3.6/site-packages/requests/models.py", line 387, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '/apigw/managementapi/get_api_public_key/': No schema supplied. Perhaps you meant http:///apigw/managementapi/get_api_public_key/?
ERROR [2021-06-29 11:07:51] [072995151c6540aa95feca3b9f52f093] backend.components.apigw /Users/jamesge/GitHubProjects/bk-bcs-saas/bcs-app/backend/components/apigw.py 31 get_api_public_key 62844 4648758784 
 	 get api public key failed: 第三方请求失败，Invalid URL '/apigw/managementapi/get_api_public_key/': No schema supplied. Perhaps you meant http:///apigw/managementapi/get_api_public_key/? 
Traceback (most recent call last):
  File "/Users/jamesge/GitHubProjects/bk-bcs-saas/bcs-app/backend/apis/constants.py", line 25, in <module>
    BCS_APP_APIGW_PUBLIC_KEY = getattr(settings, 'BCS_APP_APIGW_PUBLIC_KEY')
  File "/Users/jamesge/.local/share/virtualenvs/paas-web-backend-ce-js1Hoyit/lib/python3.6/site-packages/django/conf/__init__.py", line 57, in __getattr__
    val = getattr(self._wrapped, name)
AttributeError: 'Settings' object has no attribute 'BCS_APP_APIGW_PUBLIC_KEY'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jamesge/GitHubProjects/bk-bcs-saas/bcs-app/backend/utils/requests.py", line 52, in _request
    resp = rpool.request(method, url, params=params, data=data, json=json, headers=headers, **kwargs)
  File "/Users/jamesge/.local/share/virtualenvs/paas-web-backend-ce-js1Hoyit/lib/python3.6/site-packages/requests/sessions.py", line 519, in request
    prep = self.prepare_request(req)
  File "/Users/jamesge/.local/share/virtualenvs/paas-web-backend-ce-js1Hoyit/lib/python3.6/site-packages/requests/sessions.py", line 462, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/Users/jamesge/.local/share/virtualenvs/paas-web-backend-ce-js1Hoyit/lib/python3.6/site-packages/requests/models.py", line 313, in prepare
    self.prepare_url(url, params)
  File "/Users/jamesge/.local/share/virtualenvs/paas-web-backend-ce-js1Hoyit/lib/python3.6/site-packages/requests/models.py", line 387, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '/apigw/managementapi/get_api_public_key/': No schema supplied. Perhaps you meant http:///apigw/managementapi/get_api_public_key/?

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jamesge/GitHubProjects/bk-bcs-saas/bcs-app/backend/components/apigw.py", line 28, in get_api_public_key
    data = requests.bk_get(url, params=params, headers=headers)
  File "/Users/jamesge/GitHubProjects/bk-bcs-saas/bcs-app/backend/utils/decorators.py", line 116, in _wrapped_func
    resp = func(*args, **kwargs)
  File "/Users/jamesge/GitHubProjects/bk-bcs-saas/bcs-app/backend/utils/requests.py", line 62, in _request
    raise ComponentError(err_msg or error)
backend.utils.exceptions.ComponentError: 第三方请求失败，Invalid URL '/apigw/managementapi/get_api_public_key/': No schema supplied. Perhaps you meant http:///apigw/managementapi/get_api_public_key/?
DEBUG [2021-06-29 11:08:12] [e759f1089070493f98a62c5c2c7f8747] backend.apps.whitelist /Users/jamesge/GitHubProjects/bk-bcs-saas/bcs-app/backend/apps/whitelist.py 47 <module> 62872 4681563648 
 	 Load extension failed: No module named 'backend.apps.whitelist_ext' 

DEBUG [2021-06-29 11:08:12] [76f351c9de2f41d2bdf7e5361533e28d] backend.apps.constants /Users/jamesge/GitHubProjects/bk-bcs-saas/bcs-app/backend/apps/constants.py 148 <module> 62872 4681563648 
 	 Load extension failed: No module named 'backend.apps.constants_ext' 

DEBUG [2021-06-29 11:08:12] [7cf80ef0189b45efbd4f377137958f59] backend.components.paas_cc /Users/jamesge/GitHubProjects/bk-bcs-saas/bcs-app/backend/components/paas_cc.py 587 <module> 62872 4681563648 
 	 Load extension failed: No module named 'backend.components.paas_cc_ext' 

DEBUG [2021-06-29 11:08:12] [3c5114b9f59a4e389b438aab65915c0b] backend.bcs_k8s.helm.constants /Users/jamesge/GitHubProjects/bk-bcs-saas/bcs-app/backend/bcs_k8s/helm/constants.py 60 <module> 62872 4681563648 
 	 Load extension failed: No module named 'backend.bcs_k8s.helm.constants_ext' 

DEBUG [2021-06-29 11:08:12] [3e6f976201824715a751e50219c37737] backend.bcs_k8s.helm.utils.repo_bk /Users/jamesge/GitHubProjects/bk-bcs-saas/bcs-app/backend/bcs_k8s/helm/utils/repo_bk.py 72 <module> 62872 4681563648 
 	 Load extension failed: No module named 'backend.bcs_k8s.helm.utils.repo_ext' 

DEBUG [2021-06-29 11:08:12] [33f4b05ca1794dbd8e8133fee8d4cc9a] backend.accounts.bcs_perm /Users/jamesge/GitHubProjects/bk-bcs-saas/bcs-app/backend/accounts/bcs_perm/__init__.py 266 <module> 62872 4681563648 
 	 Load extension failed: No module named 'backend.accounts.bcs_perm.perm_ext' 

DEBUG [2021-06-29 11:08:12] [7aeffb677e4a438bba53e7d26729d5fa] backend.accounts.bcs_perm.tasks /Users/jamesge/GitHubProjects/bk-bcs-saas/bcs-app/backend/accounts/bcs_perm/tasks.py 27 <module> 62872 4681563648 
 	 Load extension failed: No module named 'backend.accounts.bcs_perm.tasks_ext' 

DEBUG [2021-06-29 11:08:12] [24e0243d99004482837d865ccdd83495] backend.components.ops /Users/jamesge/GitHubProjects/bk-bcs-saas/bcs-app/backend/components/ops.py 186 <module> 62872 4681563648 
 	 Load ops_ext failed, No module named 'backend.components.ops_ext' 

DEBUG [2021-06-29 11:08:12] [9b23401b813f4df79041329bade1f62b] backend.components.paas_auth /Users/jamesge/GitHubProjects/bk-bcs-saas/bcs-app/backend/components/paas_auth.py 50 <module> 62872 4681563648 
 	 Load extension failed: No module named 'backend.components.paas_auth_ext' 

DEBUG [2021-06-29 11:08:12] [1fa0fc39bc8546dda5caec73e66cdac9] backend.apps.cluster.tasks /Users/jamesge/GitHubProjects/bk-bcs-saas/bcs-app/backend/apps/cluster/tasks.py 242 <module> 62872 4681563648 
 	 Load extension failed: No module named 'backend.apps.cluster.tasks_ext' 

DEBUG [2021-06-29 11:08:12] [dab6174b8f4e4dac9e1228d252bb7049] backend.components.ticket /Users/jamesge/GitHubProjects/bk-bcs-saas/bcs-app/backend/components/ticket.py 90 <module> 62872 4681563648 
 	 `patch_ticket_client` hook not found, will skip 

DEBUG [2021-06-29 11:08:12] [54ada3883cb847fbac70aa9396ab18b2] backend.components.cc /Users/jamesge/GitHubProjects/bk-bcs-saas/bcs-app/backend/components/cc.py 337 <module> 62872 4681563648 
 	 Load extension failed: No module named 'backend.components.cc_ext' 

DEBUG [2021-06-29 11:08:12] [a1b8e9c2b5914d648a64cd5bbe8c1b21] backend.utils.authentication /Users/jamesge/GitHubProjects/bk-bcs-saas/bcs-app/backend/utils/authentication.py 172 <module> 62872 4681563648 
 	 Load extension failed: No module named 'backend.utils.authentication_ext' 

DEBUG [2021-06-29 11:08:12] [ea061106793b409486a06a64c29e392e] backend.apps.depot.api /Users/jamesge/GitHubProjects/bk-bcs-saas/bcs-app/backend/apps/depot/api.py 178 <module> 62872 4681563648 
 	 Load extension failed: No module named 'backend.apps.depot.api_ext' 

DEBUG [2021-06-29 11:08:12] [431ec781e0ff42d29414b77993b19a67] backend.bcs_k8s.helm.providers.constants /Users/jamesge/GitHubProjects/bk-bcs-saas/bcs-app/backend/bcs_k8s/helm/providers/constants.py 28 <module> 62872 4681563648 
 	 Load extension for constants failed 

DEBUG [2021-06-29 11:08:12] [fbbb51a9ad5d449797382c8bca4f0bed] backend.apps.projects.utils /Users/jamesge/GitHubProjects/bk-bcs-saas/bcs-app/backend/apps/projects/utils.py 68 <module> 62872 4681563648 
 	 Load extension failed: No module named 'backend.apps.projects.utils_ext' 

DEBUG [2021-06-29 11:08:12] [04f785e203b141cb953134113a45471d] backend.apps.projects.views /Users/jamesge/GitHubProjects/bk-bcs-saas/bcs-app/backend/apps/projects/views.py 314 <module> 62872 4681563648 
 	 Load extension failed: No module named 'backend.apps.projects.views_ext' 

DEBUG [2021-06-29 11:08:12] [4df55bf4f879413d99a3cb8bd7751d27] backend.components.data.constants /Users/jamesge/GitHubProjects/bk-bcs-saas/bcs-app/backend/components/data/constants.py 58 <module> 62872 4681563648 
 	 Load extension failed: No module named 'backend.components.data.constants_ext' 

DEBUG [2021-06-29 11:08:12] [f5ad7f78b073444e869afc2d2ce4cdfc] backend.components.data.databus /Users/jamesge/GitHubProjects/bk-bcs-saas/bcs-app/backend/components/data/databus.py 390 <module> 62872 4681563648 
 	 Load extension failed: No module named 'backend.components.data.databus_ext' 

DEBUG [2021-06-29 11:08:12] [2ca4ac8e164a40a695c193595ebe2659] backend.components.gse /Users/jamesge/GitHubProjects/bk-bcs-saas/bcs-app/backend/components/gse.py 48 <module> 62872 4681563648 
 	 Load extension failed: No module named 'backend.components.gse_ext' 

DEBUG [2021-06-29 11:08:12] [8411e94c67ba4b70ae32ef6229bf76e0] backend.web_console.constant_bk /Users/jamesge/GitHubProjects/bk-bcs-saas/bcs-app/backend/web_console/constant_bk.py 44 <module> 62872 4681563648 
 	 constant extension "constant_ext" module not found 

DEBUG [2021-06-29 11:08:13] [ff6331d59c7b4d779db3d0eac4862043] backend.apps.network.ext_routes /Users/jamesge/GitHubProjects/bk-bcs-saas/bcs-app/backend/apps/network/ext_routes.py 30 <module> 62872 4681563648 
 	 Load extension failed: No module named 'backend.apps.network.ext_routes_ext' 

DEBUG [2021-06-29 11:08:13] [48cbef281776441faeadc2974b8731e2] backend.apps.network.utils /Users/jamesge/GitHubProjects/bk-bcs-saas/bcs-app/backend/apps/network/utils.py 339 <module> 62872 4681563648 
 	 Load extension failed: No module named 'backend.apps.network.utils_ext' 

DEBUG [2021-06-29 11:08:13] [a5cfb86ba5924c8989dbd8734c31b43a] backend.bcs_k8s.app.repo /Users/jamesge/GitHubProjects/bk-bcs-saas/bcs-app/backend/bcs_k8s/app/repo.py 48 <module> 62872 4681563648 
 	 Load extension failed: No module named 'backend.bcs_k8s.app.repo_ext' 

ERROR [2021-06-29 11:08:13] [a551382f241b46c69fb9d12b9bb301a3] backend.utils.requests /Users/jamesge/GitHubProjects/bk-bcs-saas/bcs-app/backend/utils/requests.py 61 _request 62872 4681563648 
 	 第三方请求异常，url: /apigw/managementapi/get_api_public_key/, Invalid URL '/apigw/managementapi/get_api_public_key/': No schema supplied. Perhaps you meant http:///apigw/managementapi/get_api_public_key/? 
Traceback (most recent call last):
  File "/Users/jamesge/GitHubProjects/bk-bcs-saas/bcs-app/backend/bcs_web/constants.py", line 25, in <module>
    BCS_APP_APIGW_PUBLIC_KEY = getattr(settings, 'BCS_APP_APIGW_PUBLIC_KEY')
  File "/Users/jamesge/.local/share/virtualenvs/paas-web-backend-ce-js1Hoyit/lib/python3.6/site-packages/django/conf/__init__.py", line 57, in __getattr__
    val = getattr(self._wrapped, name)
AttributeError: 'Settings' object has no attribute 'BCS_APP_APIGW_PUBLIC_KEY'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jamesge/GitHubProjects/bk-bcs-saas/bcs-app/backend/utils/requests.py", line 52, in _request
    resp = rpool.request(method, url, params=params, data=data, json=json, headers=headers, **kwargs)
  File "/Users/jamesge/.local/share/virtualenvs/paas-web-backend-ce-js1Hoyit/lib/python3.6/site-packages/requests/sessions.py", line 519, in request
    prep = self.prepare_request(req)
  File "/Users/jamesge/.local/share/virtualenvs/paas-web-backend-ce-js1Hoyit/lib/python3.6/site-packages/requests/sessions.py", line 462, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/Users/jamesge/.local/share/virtualenvs/paas-web-backend-ce-js1Hoyit/lib/python3.6/site-packages/requests/models.py", line 313, in prepare
    self.prepare_url(url, params)
  File "/Users/jamesge/.local/share/virtualenvs/paas-web-backend-ce-js1Hoyit/lib/python3.6/site-packages/requests/models.py", line 387, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '/apigw/managementapi/get_api_public_key/': No schema supplied. Perhaps you meant http:///apigw/managementapi/get_api_public_key/?
ERROR [2021-06-29 11:08:13] [bb8b3fcbfb2b436d966354a4fa5f3b4d] backend.components.apigw /Users/jamesge/GitHubProjects/bk-bcs-saas/bcs-app/backend/components/apigw.py 31 get_api_public_key 62872 4681563648 
 	 get api public key failed: 第三方请求失败，Invalid URL '/apigw/managementapi/get_api_public_key/': No schema supplied. Perhaps you meant http:///apigw/managementapi/get_api_public_key/? 
Traceback (most recent call last):
  File "/Users/jamesge/GitHubProjects/bk-bcs-saas/bcs-app/backend/bcs_web/constants.py", line 25, in <module>
    BCS_APP_APIGW_PUBLIC_KEY = getattr(settings, 'BCS_APP_APIGW_PUBLIC_KEY')
  File "/Users/jamesge/.local/share/virtualenvs/paas-web-backend-ce-js1Hoyit/lib/python3.6/site-packages/django/conf/__init__.py", line 57, in __getattr__
    val = getattr(self._wrapped, name)
AttributeError: 'Settings' object has no attribute 'BCS_APP_APIGW_PUBLIC_KEY'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jamesge/GitHubProjects/bk-bcs-saas/bcs-app/backend/utils/requests.py", line 52, in _request
    resp = rpool.request(method, url, params=params, data=data, json=json, headers=headers, **kwargs)
  File "/Users/jamesge/.local/share/virtualenvs/paas-web-backend-ce-js1Hoyit/lib/python3.6/site-packages/requests/sessions.py", line 519, in request
    prep = self.prepare_request(req)
  File "/Users/jamesge/.local/share/virtualenvs/paas-web-backend-ce-js1Hoyit/lib/python3.6/site-packages/requests/sessions.py", line 462, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/Users/jamesge/.local/share/virtualenvs/paas-web-backend-ce-js1Hoyit/lib/python3.6/site-packages/requests/models.py", line 313, in prepare
    self.prepare_url(url, params)
  File "/Users/jamesge/.local/share/virtualenvs/paas-web-backend-ce-js1Hoyit/lib/python3.6/site-packages/requests/models.py", line 387, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '/apigw/managementapi/get_api_public_key/': No schema supplied. Perhaps you meant http:///apigw/managementapi/get_api_public_key/?

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jamesge/GitHubProjects/bk-bcs-saas/bcs-app/backend/components/apigw.py", line 28, in get_api_public_key
    data = requests.bk_get(url, params=params, headers=headers)
  File "/Users/jamesge/GitHubProjects/bk-bcs-saas/bcs-app/backend/utils/decorators.py", line 116, in _wrapped_func
    resp = func(*args, **kwargs)
  File "/Users/jamesge/GitHubProjects/bk-bcs-saas/bcs-app/backend/utils/requests.py", line 62, in _request
    raise ComponentError(err_msg or error)
backend.utils.exceptions.ComponentError: 第三方请求失败，Invalid URL '/apigw/managementapi/get_api_public_key/': No schema supplied. Perhaps you meant http:///apigw/managementapi/get_api_public_key/?
DEBUG [2021-06-29 11:08:13] [22ca428a6f854ff19169562cd93f1056] backend.components.bk_repo /Users/jamesge/GitHubProjects/bk-bcs-saas/bcs-app/backend/components/bk_repo.py 68 <module> 62872 4681563648 
 	 Load extension failed: No module named 'backend.components.bk_repo_ext' 

ERROR [2021-06-29 11:08:13] [a96c345fc3b9490eb157019325608e30] backend.utils.requests /Users/jamesge/GitHubProjects/bk-bcs-saas/bcs-app/backend/utils/requests.py 61 _request 62872 4681563648 
 	 第三方请求异常，url: /apigw/managementapi/get_api_public_key/, Invalid URL '/apigw/managementapi/get_api_public_key/': No schema supplied. Perhaps you meant http:///apigw/managementapi/get_api_public_key/? 
Traceback (most recent call last):
  File "/Users/jamesge/GitHubProjects/bk-bcs-saas/bcs-app/backend/utils/requests.py", line 52, in _request
    resp = rpool.request(method, url, params=params, data=data, json=json, headers=headers, **kwargs)
  File "/Users/jamesge/.local/share/virtualenvs/paas-web-backend-ce-js1Hoyit/lib/python3.6/site-packages/requests/sessions.py", line 519, in request
    prep = self.prepare_request(req)
  File "/Users/jamesge/.local/share/virtualenvs/paas-web-backend-ce-js1Hoyit/lib/python3.6/site-packages/requests/sessions.py", line 462, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/Users/jamesge/.local/share/virtualenvs/paas-web-backend-ce-js1Hoyit/lib/python3.6/site-packages/requests/models.py", line 313, in prepare
    self.prepare_url(url, params)
  File "/Users/jamesge/.local/share/virtualenvs/paas-web-backend-ce-js1Hoyit/lib/python3.6/site-packages/requests/models.py", line 387, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '/apigw/managementapi/get_api_public_key/': No schema supplied. Perhaps you meant http:///apigw/managementapi/get_api_public_key/?
ERROR [2021-06-29 11:08:13] [bcbc88014b3f430f9b7cb45764c93ad9] backend.components.apigw /Users/jamesge/GitHubProjects/bk-bcs-saas/bcs-app/backend/components/apigw.py 31 get_api_public_key 62872 4681563648 
 	 get api public key failed: 第三方请求失败，Invalid URL '/apigw/managementapi/get_api_public_key/': No schema supplied. Perhaps you meant http:///apigw/managementapi/get_api_public_key/? 
Traceback (most recent call last):
  File "/Users/jamesge/GitHubProjects/bk-bcs-saas/bcs-app/backend/utils/requests.py", line 52, in _request
    resp = rpool.request(method, url, params=params, data=data, json=json, headers=headers, **kwargs)
  File "/Users/jamesge/.local/share/virtualenvs/paas-web-backend-ce-js1Hoyit/lib/python3.6/site-packages/requests/sessions.py", line 519, in request
    prep = self.prepare_request(req)
  File "/Users/jamesge/.local/share/virtualenvs/paas-web-backend-ce-js1Hoyit/lib/python3.6/site-packages/requests/sessions.py", line 462, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/Users/jamesge/.local/share/virtualenvs/paas-web-backend-ce-js1Hoyit/lib/python3.6/site-packages/requests/models.py", line 313, in prepare
    self.prepare_url(url, params)
  File "/Users/jamesge/.local/share/virtualenvs/paas-web-backend-ce-js1Hoyit/lib/python3.6/site-packages/requests/models.py", line 387, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '/apigw/managementapi/get_api_public_key/': No schema supplied. Perhaps you meant http:///apigw/managementapi/get_api_public_key/?

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jamesge/GitHubProjects/bk-bcs-saas/bcs-app/backend/components/apigw.py", line 28, in get_api_public_key
    data = requests.bk_get(url, params=params, headers=headers)
  File "/Users/jamesge/GitHubProjects/bk-bcs-saas/bcs-app/backend/utils/decorators.py", line 116, in _wrapped_func
    resp = func(*args, **kwargs)
  File "/Users/jamesge/GitHubProjects/bk-bcs-saas/bcs-app/backend/utils/requests.py", line 62, in _request
    raise ComponentError(err_msg or error)
backend.utils.exceptions.ComponentError: 第三方请求失败，Invalid URL '/apigw/managementapi/get_api_public_key/': No schema supplied. Perhaps you meant http:///apigw/managementapi/get_api_public_key/?
DEBUG [2021-06-29 11:08:13] [c35a4fab4fde41dbbe85f7f845b3a992] backend.apps.apis.constants /Users/jamesge/GitHubProjects/bk-bcs-saas/bcs-app/backend/apps/apis/constants.py 40 <module> 62872 4681563648 
 	 Load extension failed: No module named 'backend.apps.apis.constants_ext' 

ERROR [2021-06-29 11:08:13] [422ea3c05196471f898690cf7703d69a] backend.utils.requests /Users/jamesge/GitHubProjects/bk-bcs-saas/bcs-app/backend/utils/requests.py 61 _request 62872 4681563648 
 	 第三方请求异常，url: /apigw/managementapi/get_api_public_key/, Invalid URL '/apigw/managementapi/get_api_public_key/': No schema supplied. Perhaps you meant http:///apigw/managementapi/get_api_public_key/? 
Traceback (most recent call last):
  File "/Users/jamesge/GitHubProjects/bk-bcs-saas/bcs-app/backend/apis/constants.py", line 25, in <module>
    BCS_APP_APIGW_PUBLIC_KEY = getattr(settings, 'BCS_APP_APIGW_PUBLIC_KEY')
  File "/Users/jamesge/.local/share/virtualenvs/paas-web-backend-ce-js1Hoyit/lib/python3.6/site-packages/django/conf/__init__.py", line 57, in __getattr__
    val = getattr(self._wrapped, name)
AttributeError: 'Settings' object has no attribute 'BCS_APP_APIGW_PUBLIC_KEY'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jamesge/GitHubProjects/bk-bcs-saas/bcs-app/backend/utils/requests.py", line 52, in _request
    resp = rpool.request(method, url, params=params, data=data, json=json, headers=headers, **kwargs)
  File "/Users/jamesge/.local/share/virtualenvs/paas-web-backend-ce-js1Hoyit/lib/python3.6/site-packages/requests/sessions.py", line 519, in request
    prep = self.prepare_request(req)
  File "/Users/jamesge/.local/share/virtualenvs/paas-web-backend-ce-js1Hoyit/lib/python3.6/site-packages/requests/sessions.py", line 462, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/Users/jamesge/.local/share/virtualenvs/paas-web-backend-ce-js1Hoyit/lib/python3.6/site-packages/requests/models.py", line 313, in prepare
    self.prepare_url(url, params)
  File "/Users/jamesge/.local/share/virtualenvs/paas-web-backend-ce-js1Hoyit/lib/python3.6/site-packages/requests/models.py", line 387, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '/apigw/managementapi/get_api_public_key/': No schema supplied. Perhaps you meant http:///apigw/managementapi/get_api_public_key/?
ERROR [2021-06-29 11:08:13] [98b9468fde65400186aec430cb46255d] backend.components.apigw /Users/jamesge/GitHubProjects/bk-bcs-saas/bcs-app/backend/components/apigw.py 31 get_api_public_key 62872 4681563648 
 	 get api public key failed: 第三方请求失败，Invalid URL '/apigw/managementapi/get_api_public_key/': No schema supplied. Perhaps you meant http:///apigw/managementapi/get_api_public_key/? 
Traceback (most recent call last):
  File "/Users/jamesge/GitHubProjects/bk-bcs-saas/bcs-app/backend/apis/constants.py", line 25, in <module>
    BCS_APP_APIGW_PUBLIC_KEY = getattr(settings, 'BCS_APP_APIGW_PUBLIC_KEY')
  File "/Users/jamesge/.local/share/virtualenvs/paas-web-backend-ce-js1Hoyit/lib/python3.6/site-packages/django/conf/__init__.py", line 57, in __getattr__
    val = getattr(self._wrapped, name)
AttributeError: 'Settings' object has no attribute 'BCS_APP_APIGW_PUBLIC_KEY'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jamesge/GitHubProjects/bk-bcs-saas/bcs-app/backend/utils/requests.py", line 52, in _request
    resp = rpool.request(method, url, params=params, data=data, json=json, headers=headers, **kwargs)
  File "/Users/jamesge/.local/share/virtualenvs/paas-web-backend-ce-js1Hoyit/lib/python3.6/site-packages/requests/sessions.py", line 519, in request
    prep = self.prepare_request(req)
  File "/Users/jamesge/.local/share/virtualenvs/paas-web-backend-ce-js1Hoyit/lib/python3.6/site-packages/requests/sessions.py", line 462, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/Users/jamesge/.local/share/virtualenvs/paas-web-backend-ce-js1Hoyit/lib/python3.6/site-packages/requests/models.py", line 313, in prepare
    self.prepare_url(url, params)
  File "/Users/jamesge/.local/share/virtualenvs/paas-web-backend-ce-js1Hoyit/lib/python3.6/site-packages/requests/models.py", line 387, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '/apigw/managementapi/get_api_public_key/': No schema supplied. Perhaps you meant http:///apigw/managementapi/get_api_public_key/?

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jamesge/GitHubProjects/bk-bcs-saas/bcs-app/backend/components/apigw.py", line 28, in get_api_public_key
    data = requests.bk_get(url, params=params, headers=headers)
  File "/Users/jamesge/GitHubProjects/bk-bcs-saas/bcs-app/backend/utils/decorators.py", line 116, in _wrapped_func
    resp = func(*args, **kwargs)
  File "/Users/jamesge/GitHubProjects/bk-bcs-saas/bcs-app/backend/utils/requests.py", line 62, in _request
    raise ComponentError(err_msg or error)
backend.utils.exceptions.ComponentError: 第三方请求失败，Invalid URL '/apigw/managementapi/get_api_public_key/': No schema supplied. Perhaps you meant http:///apigw/managementapi/get_api_public_key/?
DEBUG [2021-06-29 11:10:14] [3466945defdf4614b80aa89ca53d360f] backend.apps.whitelist /Users/jamesge/GitHubProjects/bk-bcs-saas/bcs-app/backend/apps/whitelist.py 47 <module> 63170 4433776128 
 	 Load extension failed: No module named 'backend.apps.whitelist_ext' 

DEBUG [2021-06-29 11:10:14] [bb30709dc13e4c1ab31bd7c71e9f6bc4] backend.apps.constants /Users/jamesge/GitHubProjects/bk-bcs-saas/bcs-app/backend/apps/constants.py 148 <module> 63170 4433776128 
 	 Load extension failed: No module named 'backend.apps.constants_ext' 

DEBUG [2021-06-29 11:10:14] [4f5406b211574f5cb179fa4b09d7a90d] backend.components.paas_cc /Users/jamesge/GitHubProjects/bk-bcs-saas/bcs-app/backend/components/paas_cc.py 587 <module> 63170 4433776128 
 	 Load extension failed: No module named 'backend.components.paas_cc_ext' 

DEBUG [2021-06-29 11:10:14] [4c5446c26f7347fd928cc4cd5e799f2d] backend.bcs_k8s.helm.constants /Users/jamesge/GitHubProjects/bk-bcs-saas/bcs-app/backend/bcs_k8s/helm/constants.py 60 <module> 63170 4433776128 
 	 Load extension failed: No module named 'backend.bcs_k8s.helm.constants_ext' 

DEBUG [2021-06-29 11:10:14] [5213abdb5b084966aacce85a130f0fba] backend.bcs_k8s.helm.utils.repo_bk /Users/jamesge/GitHubProjects/bk-bcs-saas/bcs-app/backend/bcs_k8s/helm/utils/repo_bk.py 72 <module> 63170 4433776128 
 	 Load extension failed: No module named 'backend.bcs_k8s.helm.utils.repo_ext' 

DEBUG [2021-06-29 11:10:14] [d8b43674fc4348aab63c8d25f02d6632] backend.accounts.bcs_perm /Users/jamesge/GitHubProjects/bk-bcs-saas/bcs-app/backend/accounts/bcs_perm/__init__.py 266 <module> 63170 4433776128 
 	 Load extension failed: No module named 'backend.accounts.bcs_perm.perm_ext' 

DEBUG [2021-06-29 11:10:14] [ffefdb5f1c874e22986a2e0be7509fc6] backend.accounts.bcs_perm.tasks /Users/jamesge/GitHubProjects/bk-bcs-saas/bcs-app/backend/accounts/bcs_perm/tasks.py 27 <module> 63170 4433776128 
 	 Load extension failed: No module named 'backend.accounts.bcs_perm.tasks_ext' 

DEBUG [2021-06-29 11:10:14] [77178ed30723404eac9efdde7bf9fefe] backend.components.ops /Users/jamesge/GitHubProjects/bk-bcs-saas/bcs-app/backend/components/ops.py 186 <module> 63170 4433776128 
 	 Load ops_ext failed, No module named 'backend.components.ops_ext' 

DEBUG [2021-06-29 11:10:14] [118608ae735f4daabb5af5238863eedc] backend.components.paas_auth /Users/jamesge/GitHubProjects/bk-bcs-saas/bcs-app/backend/components/paas_auth.py 50 <module> 63170 4433776128 
 	 Load extension failed: No module named 'backend.components.paas_auth_ext' 

DEBUG [2021-06-29 11:10:14] [b8494b47ed2542e196650581160e7798] backend.apps.cluster.tasks /Users/jamesge/GitHubProjects/bk-bcs-saas/bcs-app/backend/apps/cluster/tasks.py 242 <module> 63170 4433776128 
 	 Load extension failed: No module named 'backend.apps.cluster.tasks_ext' 

DEBUG [2021-06-29 11:10:15] [3dc910f7c3d546ceb185c05c797eb017] backend.components.ticket /Users/jamesge/GitHubProjects/bk-bcs-saas/bcs-app/backend/components/ticket.py 90 <module> 63170 4433776128 
 	 `patch_ticket_client` hook not found, will skip 

DEBUG [2021-06-29 11:10:15] [29ac1f9dac074754b9779f2e733663a5] backend.components.cc /Users/jamesge/GitHubProjects/bk-bcs-saas/bcs-app/backend/components/cc.py 337 <module> 63170 4433776128 
 	 Load extension failed: No module named 'backend.components.cc_ext' 

DEBUG [2021-06-29 11:10:15] [56e9b1704a854c5fa8dbf2941abb1f13] backend.utils.authentication /Users/jamesge/GitHubProjects/bk-bcs-saas/bcs-app/backend/utils/authentication.py 172 <module> 63170 4433776128 
 	 Load extension failed: No module named 'backend.utils.authentication_ext' 

DEBUG [2021-06-29 11:10:15] [0bfaaae738bb4df9a431feb5157b59d3] backend.apps.depot.api /Users/jamesge/GitHubProjects/bk-bcs-saas/bcs-app/backend/apps/depot/api.py 178 <module> 63170 4433776128 
 	 Load extension failed: No module named 'backend.apps.depot.api_ext' 

DEBUG [2021-06-29 11:10:15] [4a72bdd2eaa94a69b4c14fa739fed9cc] backend.bcs_k8s.helm.providers.constants /Users/jamesge/GitHubProjects/bk-bcs-saas/bcs-app/backend/bcs_k8s/helm/providers/constants.py 28 <module> 63170 4433776128 
 	 Load extension for constants failed 

DEBUG [2021-06-29 11:10:15] [c7ef9cfb5fe648b08e3f58e5cbd7747f] backend.apps.projects.utils /Users/jamesge/GitHubProjects/bk-bcs-saas/bcs-app/backend/apps/projects/utils.py 68 <module> 63170 4433776128 
 	 Load extension failed: No module named 'backend.apps.projects.utils_ext' 

DEBUG [2021-06-29 11:10:15] [e8150bf849ad49b4be9dcd7fba3f26d9] backend.apps.projects.views /Users/jamesge/GitHubProjects/bk-bcs-saas/bcs-app/backend/apps/projects/views.py 314 <module> 63170 4433776128 
 	 Load extension failed: No module named 'backend.apps.projects.views_ext' 

DEBUG [2021-06-29 11:10:15] [97bf7066c3534924a47930d7c735bdb8] backend.components.data.constants /Users/jamesge/GitHubProjects/bk-bcs-saas/bcs-app/backend/components/data/constants.py 58 <module> 63170 4433776128 
 	 Load extension failed: No module named 'backend.components.data.constants_ext' 

DEBUG [2021-06-29 11:10:15] [465d01d808ea41a4a605cce5f19e5dea] backend.components.data.databus /Users/jamesge/GitHubProjects/bk-bcs-saas/bcs-app/backend/components/data/databus.py 390 <module> 63170 4433776128 
 	 Load extension failed: No module named 'backend.components.data.databus_ext' 

DEBUG [2021-06-29 11:10:15] [e92cc0078e95456abf80623827f1aac8] backend.components.gse /Users/jamesge/GitHubProjects/bk-bcs-saas/bcs-app/backend/components/gse.py 48 <module> 63170 4433776128 
 	 Load extension failed: No module named 'backend.components.gse_ext' 

DEBUG [2021-06-29 11:10:15] [50f8fa35b0e343a29655a9681903daec] backend.web_console.constant_bk /Users/jamesge/GitHubProjects/bk-bcs-saas/bcs-app/backend/web_console/constant_bk.py 44 <module> 63170 4433776128 
 	 constant extension "constant_ext" module not found 

DEBUG [2021-06-29 11:10:15] [ccf3bfc55b9d48dbac1327a81996fb61] backend.apps.network.ext_routes /Users/jamesge/GitHubProjects/bk-bcs-saas/bcs-app/backend/apps/network/ext_routes.py 30 <module> 63170 4433776128 
 	 Load extension failed: No module named 'backend.apps.network.ext_routes_ext' 

DEBUG [2021-06-29 11:10:15] [d9422a29ce2147b2a35952e4ea8dbae9] backend.apps.network.utils /Users/jamesge/GitHubProjects/bk-bcs-saas/bcs-app/backend/apps/network/utils.py 339 <module> 63170 4433776128 
 	 Load extension failed: No module named 'backend.apps.network.utils_ext' 

DEBUG [2021-06-29 11:10:15] [14f432149672486d81e614fd3edb07c7] backend.bcs_k8s.app.repo /Users/jamesge/GitHubProjects/bk-bcs-saas/bcs-app/backend/bcs_k8s/app/repo.py 48 <module> 63170 4433776128 
 	 Load extension failed: No module named 'backend.bcs_k8s.app.repo_ext' 

ERROR [2021-06-29 11:10:15] [b24094919302409284c5875a661f50b9] backend.utils.requests /Users/jamesge/GitHubProjects/bk-bcs-saas/bcs-app/backend/utils/requests.py 61 _request 63170 4433776128 
 	 第三方请求异常，url: /apigw/managementapi/get_api_public_key/, Invalid URL '/apigw/managementapi/get_api_public_key/': No schema supplied. Perhaps you meant http:///apigw/managementapi/get_api_public_key/? 
Traceback (most recent call last):
  File "/Users/jamesge/GitHubProjects/bk-bcs-saas/bcs-app/backend/bcs_web/constants.py", line 25, in <module>
    BCS_APP_APIGW_PUBLIC_KEY = getattr(settings, 'BCS_APP_APIGW_PUBLIC_KEY')
  File "/Users/jamesge/.local/share/virtualenvs/paas-web-backend-ce-js1Hoyit/lib/python3.6/site-packages/django/conf/__init__.py", line 57, in __getattr__
    val = getattr(self._wrapped, name)
AttributeError: 'Settings' object has no attribute 'BCS_APP_APIGW_PUBLIC_KEY'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jamesge/GitHubProjects/bk-bcs-saas/bcs-app/backend/utils/requests.py", line 52, in _request
    resp = rpool.request(method, url, params=params, data=data, json=json, headers=headers, **kwargs)
  File "/Users/jamesge/.local/share/virtualenvs/paas-web-backend-ce-js1Hoyit/lib/python3.6/site-packages/requests/sessions.py", line 519, in request
    prep = self.prepare_request(req)
  File "/Users/jamesge/.local/share/virtualenvs/paas-web-backend-ce-js1Hoyit/lib/python3.6/site-packages/requests/sessions.py", line 462, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/Users/jamesge/.local/share/virtualenvs/paas-web-backend-ce-js1Hoyit/lib/python3.6/site-packages/requests/models.py", line 313, in prepare
    self.prepare_url(url, params)
  File "/Users/jamesge/.local/share/virtualenvs/paas-web-backend-ce-js1Hoyit/lib/python3.6/site-packages/requests/models.py", line 387, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '/apigw/managementapi/get_api_public_key/': No schema supplied. Perhaps you meant http:///apigw/managementapi/get_api_public_key/?
ERROR [2021-06-29 11:10:15] [da84c30697f340cbbed38d86a58eaf34] backend.components.apigw /Users/jamesge/GitHubProjects/bk-bcs-saas/bcs-app/backend/components/apigw.py 31 get_api_public_key 63170 4433776128 
 	 get api public key failed: 第三方请求失败，Invalid URL '/apigw/managementapi/get_api_public_key/': No schema supplied. Perhaps you meant http:///apigw/managementapi/get_api_public_key/? 
Traceback (most recent call last):
  File "/Users/jamesge/GitHubProjects/bk-bcs-saas/bcs-app/backend/bcs_web/constants.py", line 25, in <module>
    BCS_APP_APIGW_PUBLIC_KEY = getattr(settings, 'BCS_APP_APIGW_PUBLIC_KEY')
  File "/Users/jamesge/.local/share/virtualenvs/paas-web-backend-ce-js1Hoyit/lib/python3.6/site-packages/django/conf/__init__.py", line 57, in __getattr__
    val = getattr(self._wrapped, name)
AttributeError: 'Settings' object has no attribute 'BCS_APP_APIGW_PUBLIC_KEY'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jamesge/GitHubProjects/bk-bcs-saas/bcs-app/backend/utils/requests.py", line 52, in _request
    resp = rpool.request(method, url, params=params, data=data, json=json, headers=headers, **kwargs)
  File "/Users/jamesge/.local/share/virtualenvs/paas-web-backend-ce-js1Hoyit/lib/python3.6/site-packages/requests/sessions.py", line 519, in request
    prep = self.prepare_request(req)
  File "/Users/jamesge/.local/share/virtualenvs/paas-web-backend-ce-js1Hoyit/lib/python3.6/site-packages/requests/sessions.py", line 462, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/Users/jamesge/.local/share/virtualenvs/paas-web-backend-ce-js1Hoyit/lib/python3.6/site-packages/requests/models.py", line 313, in prepare
    self.prepare_url(url, params)
  File "/Users/jamesge/.local/share/virtualenvs/paas-web-backend-ce-js1Hoyit/lib/python3.6/site-packages/requests/models.py", line 387, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '/apigw/managementapi/get_api_public_key/': No schema supplied. Perhaps you meant http:///apigw/managementapi/get_api_public_key/?

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jamesge/GitHubProjects/bk-bcs-saas/bcs-app/backend/components/apigw.py", line 28, in get_api_public_key
    data = requests.bk_get(url, params=params, headers=headers)
  File "/Users/jamesge/GitHubProjects/bk-bcs-saas/bcs-app/backend/utils/decorators.py", line 116, in _wrapped_func
    resp = func(*args, **kwargs)
  File "/Users/jamesge/GitHubProjects/bk-bcs-saas/bcs-app/backend/utils/requests.py", line 62, in _request
    raise ComponentError(err_msg or error)
backend.utils.exceptions.ComponentError: 第三方请求失败，Invalid URL '/apigw/managementapi/get_api_public_key/': No schema supplied. Perhaps you meant http:///apigw/managementapi/get_api_public_key/?
DEBUG [2021-06-29 11:10:15] [7c73fc6600344975b4d21b8c5ca96b77] backend.components.bk_repo /Users/jamesge/GitHubProjects/bk-bcs-saas/bcs-app/backend/components/bk_repo.py 68 <module> 63170 4433776128 
 	 Load extension failed: No module named 'backend.components.bk_repo_ext' 

ERROR [2021-06-29 11:10:15] [b08f1820112f4bb798abc3c3e92a5dbd] backend.utils.requests /Users/jamesge/GitHubProjects/bk-bcs-saas/bcs-app/backend/utils/requests.py 61 _request 63170 4433776128 
 	 第三方请求异常，url: /apigw/managementapi/get_api_public_key/, Invalid URL '/apigw/managementapi/get_api_public_key/': No schema supplied. Perhaps you meant http:///apigw/managementapi/get_api_public_key/? 
Traceback (most recent call last):
  File "/Users/jamesge/GitHubProjects/bk-bcs-saas/bcs-app/backend/utils/requests.py", line 52, in _request
    resp = rpool.request(method, url, params=params, data=data, json=json, headers=headers, **kwargs)
  File "/Users/jamesge/.local/share/virtualenvs/paas-web-backend-ce-js1Hoyit/lib/python3.6/site-packages/requests/sessions.py", line 519, in request
    prep = self.prepare_request(req)
  File "/Users/jamesge/.local/share/virtualenvs/paas-web-backend-ce-js1Hoyit/lib/python3.6/site-packages/requests/sessions.py", line 462, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/Users/jamesge/.local/share/virtualenvs/paas-web-backend-ce-js1Hoyit/lib/python3.6/site-packages/requests/models.py", line 313, in prepare
    self.prepare_url(url, params)
  File "/Users/jamesge/.local/share/virtualenvs/paas-web-backend-ce-js1Hoyit/lib/python3.6/site-packages/requests/models.py", line 387, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '/apigw/managementapi/get_api_public_key/': No schema supplied. Perhaps you meant http:///apigw/managementapi/get_api_public_key/?
ERROR [2021-06-29 11:10:15] [2c1bf4abb9f54786adfe2ff886ddfda8] backend.components.apigw /Users/jamesge/GitHubProjects/bk-bcs-saas/bcs-app/backend/components/apigw.py 31 get_api_public_key 63170 4433776128 
 	 get api public key failed: 第三方请求失败，Invalid URL '/apigw/managementapi/get_api_public_key/': No schema supplied. Perhaps you meant http:///apigw/managementapi/get_api_public_key/? 
Traceback (most recent call last):
  File "/Users/jamesge/GitHubProjects/bk-bcs-saas/bcs-app/backend/utils/requests.py", line 52, in _request
    resp = rpool.request(method, url, params=params, data=data, json=json, headers=headers, **kwargs)
  File "/Users/jamesge/.local/share/virtualenvs/paas-web-backend-ce-js1Hoyit/lib/python3.6/site-packages/requests/sessions.py", line 519, in request
    prep = self.prepare_request(req)
  File "/Users/jamesge/.local/share/virtualenvs/paas-web-backend-ce-js1Hoyit/lib/python3.6/site-packages/requests/sessions.py", line 462, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/Users/jamesge/.local/share/virtualenvs/paas-web-backend-ce-js1Hoyit/lib/python3.6/site-packages/requests/models.py", line 313, in prepare
    self.prepare_url(url, params)
  File "/Users/jamesge/.local/share/virtualenvs/paas-web-backend-ce-js1Hoyit/lib/python3.6/site-packages/requests/models.py", line 387, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '/apigw/managementapi/get_api_public_key/': No schema supplied. Perhaps you meant http:///apigw/managementapi/get_api_public_key/?

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jamesge/GitHubProjects/bk-bcs-saas/bcs-app/backend/components/apigw.py", line 28, in get_api_public_key
    data = requests.bk_get(url, params=params, headers=headers)
  File "/Users/jamesge/GitHubProjects/bk-bcs-saas/bcs-app/backend/utils/decorators.py", line 116, in _wrapped_func
    resp = func(*args, **kwargs)
  File "/Users/jamesge/GitHubProjects/bk-bcs-saas/bcs-app/backend/utils/requests.py", line 62, in _request
    raise ComponentError(err_msg or error)
backend.utils.exceptions.ComponentError: 第三方请求失败，Invalid URL '/apigw/managementapi/get_api_public_key/': No schema supplied. Perhaps you meant http:///apigw/managementapi/get_api_public_key/?
DEBUG [2021-06-29 11:10:15] [2364f6bbebcd471886920c2816dbf9b0] backend.apps.apis.constants /Users/jamesge/GitHubProjects/bk-bcs-saas/bcs-app/backend/apps/apis/constants.py 40 <module> 63170 4433776128 
 	 Load extension failed: No module named 'backend.apps.apis.constants_ext' 

ERROR [2021-06-29 11:10:15] [5e34fb0085dc42d896163c9db3c381be] backend.utils.requests /Users/jamesge/GitHubProjects/bk-bcs-saas/bcs-app/backend/utils/requests.py 61 _request 63170 4433776128 
 	 第三方请求异常，url: /apigw/managementapi/get_api_public_key/, Invalid URL '/apigw/managementapi/get_api_public_key/': No schema supplied. Perhaps you meant http:///apigw/managementapi/get_api_public_key/? 
Traceback (most recent call last):
  File "/Users/jamesge/GitHubProjects/bk-bcs-saas/bcs-app/backend/apis/constants.py", line 25, in <module>
    BCS_APP_APIGW_PUBLIC_KEY = getattr(settings, 'BCS_APP_APIGW_PUBLIC_KEY')
  File "/Users/jamesge/.local/share/virtualenvs/paas-web-backend-ce-js1Hoyit/lib/python3.6/site-packages/django/conf/__init__.py", line 57, in __getattr__
    val = getattr(self._wrapped, name)
AttributeError: 'Settings' object has no attribute 'BCS_APP_APIGW_PUBLIC_KEY'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jamesge/GitHubProjects/bk-bcs-saas/bcs-app/backend/utils/requests.py", line 52, in _request
    resp = rpool.request(method, url, params=params, data=data, json=json, headers=headers, **kwargs)
  File "/Users/jamesge/.local/share/virtualenvs/paas-web-backend-ce-js1Hoyit/lib/python3.6/site-packages/requests/sessions.py", line 519, in request
    prep = self.prepare_request(req)
  File "/Users/jamesge/.local/share/virtualenvs/paas-web-backend-ce-js1Hoyit/lib/python3.6/site-packages/requests/sessions.py", line 462, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/Users/jamesge/.local/share/virtualenvs/paas-web-backend-ce-js1Hoyit/lib/python3.6/site-packages/requests/models.py", line 313, in prepare
    self.prepare_url(url, params)
  File "/Users/jamesge/.local/share/virtualenvs/paas-web-backend-ce-js1Hoyit/lib/python3.6/site-packages/requests/models.py", line 387, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '/apigw/managementapi/get_api_public_key/': No schema supplied. Perhaps you meant http:///apigw/managementapi/get_api_public_key/?
ERROR [2021-06-29 11:10:15] [3c5714ac4fc142429d165f0c3c997aff] backend.components.apigw /Users/jamesge/GitHubProjects/bk-bcs-saas/bcs-app/backend/components/apigw.py 31 get_api_public_key 63170 4433776128 
 	 get api public key failed: 第三方请求失败，Invalid URL '/apigw/managementapi/get_api_public_key/': No schema supplied. Perhaps you meant http:///apigw/managementapi/get_api_public_key/? 
Traceback (most recent call last):
  File "/Users/jamesge/GitHubProjects/bk-bcs-saas/bcs-app/backend/apis/constants.py", line 25, in <module>
    BCS_APP_APIGW_PUBLIC_KEY = getattr(settings, 'BCS_APP_APIGW_PUBLIC_KEY')
  File "/Users/jamesge/.local/share/virtualenvs/paas-web-backend-ce-js1Hoyit/lib/python3.6/site-packages/django/conf/__init__.py", line 57, in __getattr__
    val = getattr(self._wrapped, name)
AttributeError: 'Settings' object has no attribute 'BCS_APP_APIGW_PUBLIC_KEY'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jamesge/GitHubProjects/bk-bcs-saas/bcs-app/backend/utils/requests.py", line 52, in _request
    resp = rpool.request(method, url, params=params, data=data, json=json, headers=headers, **kwargs)
  File "/Users/jamesge/.local/share/virtualenvs/paas-web-backend-ce-js1Hoyit/lib/python3.6/site-packages/requests/sessions.py", line 519, in request
    prep = self.prepare_request(req)
  File "/Users/jamesge/.local/share/virtualenvs/paas-web-backend-ce-js1Hoyit/lib/python3.6/site-packages/requests/sessions.py", line 462, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/Users/jamesge/.local/share/virtualenvs/paas-web-backend-ce-js1Hoyit/lib/python3.6/site-packages/requests/models.py", line 313, in prepare
    self.prepare_url(url, params)
  File "/Users/jamesge/.local/share/virtualenvs/paas-web-backend-ce-js1Hoyit/lib/python3.6/site-packages/requests/models.py", line 387, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '/apigw/managementapi/get_api_public_key/': No schema supplied. Perhaps you meant http:///apigw/managementapi/get_api_public_key/?

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jamesge/GitHubProjects/bk-bcs-saas/bcs-app/backend/components/apigw.py", line 28, in get_api_public_key
    data = requests.bk_get(url, params=params, headers=headers)
  File "/Users/jamesge/GitHubProjects/bk-bcs-saas/bcs-app/backend/utils/decorators.py", line 116, in _wrapped_func
    resp = func(*args, **kwargs)
  File "/Users/jamesge/GitHubProjects/bk-bcs-saas/bcs-app/backend/utils/requests.py", line 62, in _request
    raise ComponentError(err_msg or error)
backend.utils.exceptions.ComponentError: 第三方请求失败，Invalid URL '/apigw/managementapi/get_api_public_key/': No schema supplied. Perhaps you meant http:///apigw/managementapi/get_api_public_key/?
DEBUG [2021-06-29 11:10:44] [949c1cb24d72440f872ac07e0e8f22f3] backend.apps.whitelist /Users/jamesge/GitHubProjects/bk-bcs-saas/bcs-app/backend/apps/whitelist.py 47 <module> 63242 4772154880 
 	 Load extension failed: No module named 'backend.apps.whitelist_ext' 

DEBUG [2021-06-29 11:10:44] [7f9fe31bc4664bbf81f916344099f895] backend.apps.constants /Users/jamesge/GitHubProjects/bk-bcs-saas/bcs-app/backend/apps/constants.py 148 <module> 63242 4772154880 
 	 Load extension failed: No module named 'backend.apps.constants_ext' 

DEBUG [2021-06-29 11:10:44] [2921012e657c4eb9a05ffa9c542c27b5] backend.components.paas_cc /Users/jamesge/GitHubProjects/bk-bcs-saas/bcs-app/backend/components/paas_cc.py 587 <module> 63242 4772154880 
 	 Load extension failed: No module named 'backend.components.paas_cc_ext' 

DEBUG [2021-06-29 11:10:44] [96f1fb162201413ebc99e18ae3d8f3d5] backend.bcs_k8s.helm.constants /Users/jamesge/GitHubProjects/bk-bcs-saas/bcs-app/backend/bcs_k8s/helm/constants.py 60 <module> 63242 4772154880 
 	 Load extension failed: No module named 'backend.bcs_k8s.helm.constants_ext' 

DEBUG [2021-06-29 11:10:44] [9baf024a5dc544c28ea3b5d720bb186a] backend.bcs_k8s.helm.utils.repo_bk /Users/jamesge/GitHubProjects/bk-bcs-saas/bcs-app/backend/bcs_k8s/helm/utils/repo_bk.py 72 <module> 63242 4772154880 
 	 Load extension failed: No module named 'backend.bcs_k8s.helm.utils.repo_ext' 

DEBUG [2021-06-29 11:10:44] [685ebff6d5714dfb8a06410bd91cda66] backend.accounts.bcs_perm /Users/jamesge/GitHubProjects/bk-bcs-saas/bcs-app/backend/accounts/bcs_perm/__init__.py 266 <module> 63242 4772154880 
 	 Load extension failed: No module named 'backend.accounts.bcs_perm.perm_ext' 

DEBUG [2021-06-29 11:10:44] [919e2bd6bce24262b2abcd02b0422502] backend.accounts.bcs_perm.tasks /Users/jamesge/GitHubProjects/bk-bcs-saas/bcs-app/backend/accounts/bcs_perm/tasks.py 27 <module> 63242 4772154880 
 	 Load extension failed: No module named 'backend.accounts.bcs_perm.tasks_ext' 

DEBUG [2021-06-29 11:10:44] [275471b8d575492c95b51c316907bedc] backend.components.ops /Users/jamesge/GitHubProjects/bk-bcs-saas/bcs-app/backend/components/ops.py 186 <module> 63242 4772154880 
 	 Load ops_ext failed, No module named 'backend.components.ops_ext' 

DEBUG [2021-06-29 11:10:44] [9f13a7b3e363483e8795bf419d4fa147] backend.components.paas_auth /Users/jamesge/GitHubProjects/bk-bcs-saas/bcs-app/backend/components/paas_auth.py 50 <module> 63242 4772154880 
 	 Load extension failed: No module named 'backend.components.paas_auth_ext' 

DEBUG [2021-06-29 11:10:44] [63e5b23e808048c4ab51213283910bd4] backend.apps.cluster.tasks /Users/jamesge/GitHubProjects/bk-bcs-saas/bcs-app/backend/apps/cluster/tasks.py 242 <module> 63242 4772154880 
 	 Load extension failed: No module named 'backend.apps.cluster.tasks_ext' 

DEBUG [2021-06-29 11:10:44] [b7fc71a3e0944465bb2a4b23e12a662a] backend.components.ticket /Users/jamesge/GitHubProjects/bk-bcs-saas/bcs-app/backend/components/ticket.py 90 <module> 63242 4772154880 
 	 `patch_ticket_client` hook not found, will skip 

DEBUG [2021-06-29 11:10:44] [7a0c278211ef497893803c4a3a783c43] backend.components.cc /Users/jamesge/GitHubProjects/bk-bcs-saas/bcs-app/backend/components/cc.py 337 <module> 63242 4772154880 
 	 Load extension failed: No module named 'backend.components.cc_ext' 

DEBUG [2021-06-29 11:10:44] [bffbef1aeb5748bd8d7dae096db89a1f] backend.utils.authentication /Users/jamesge/GitHubProjects/bk-bcs-saas/bcs-app/backend/utils/authentication.py 172 <module> 63242 4772154880 
 	 Load extension failed: No module named 'backend.utils.authentication_ext' 

DEBUG [2021-06-29 11:10:44] [39c1242ce4064aafa4d6f99201858f62] backend.apps.depot.api /Users/jamesge/GitHubProjects/bk-bcs-saas/bcs-app/backend/apps/depot/api.py 178 <module> 63242 4772154880 
 	 Load extension failed: No module named 'backend.apps.depot.api_ext' 

DEBUG [2021-06-29 11:10:44] [e7a0ede8d46648d48d018359f10b894b] backend.bcs_k8s.helm.providers.constants /Users/jamesge/GitHubProjects/bk-bcs-saas/bcs-app/backend/bcs_k8s/helm/providers/constants.py 28 <module> 63242 4772154880 
 	 Load extension for constants failed 

DEBUG [2021-06-29 11:10:44] [2a6d7f5448f847178055a916bbab1fa0] backend.apps.projects.utils /Users/jamesge/GitHubProjects/bk-bcs-saas/bcs-app/backend/apps/projects/utils.py 68 <module> 63242 4772154880 
 	 Load extension failed: No module named 'backend.apps.projects.utils_ext' 

DEBUG [2021-06-29 11:10:44] [d2eba685898849e080fbf1cc1b137d51] backend.apps.projects.views /Users/jamesge/GitHubProjects/bk-bcs-saas/bcs-app/backend/apps/projects/views.py 314 <module> 63242 4772154880 
 	 Load extension failed: No module named 'backend.apps.projects.views_ext' 

DEBUG [2021-06-29 11:10:44] [2615c519efb24cbeaad7816d1d91e135] backend.components.data.constants /Users/jamesge/GitHubProjects/bk-bcs-saas/bcs-app/backend/components/data/constants.py 58 <module> 63242 4772154880 
 	 Load extension failed: No module named 'backend.components.data.constants_ext' 

DEBUG [2021-06-29 11:10:44] [fb92d567867a4c2d98220d1380cfa296] backend.components.data.databus /Users/jamesge/GitHubProjects/bk-bcs-saas/bcs-app/backend/components/data/databus.py 390 <module> 63242 4772154880 
 	 Load extension failed: No module named 'backend.components.data.databus_ext' 

DEBUG [2021-06-29 11:10:45] [db20a1fbea28473abfce69d9e99177e8] backend.components.gse /Users/jamesge/GitHubProjects/bk-bcs-saas/bcs-app/backend/components/gse.py 48 <module> 63242 4772154880 
 	 Load extension failed: No module named 'backend.components.gse_ext' 

DEBUG [2021-06-29 11:10:45] [6b6d133a70a54d0c9c7521dd0662eec8] backend.web_console.constant_bk /Users/jamesge/GitHubProjects/bk-bcs-saas/bcs-app/backend/web_console/constant_bk.py 44 <module> 63242 4772154880 
 	 constant extension "constant_ext" module not found 

DEBUG [2021-06-29 11:10:45] [ecc884116a09411f8d01c8e4ad123826] backend.apps.network.ext_routes /Users/jamesge/GitHubProjects/bk-bcs-saas/bcs-app/backend/apps/network/ext_routes.py 30 <module> 63242 4772154880 
 	 Load extension failed: No module named 'backend.apps.network.ext_routes_ext' 

DEBUG [2021-06-29 11:10:45] [88c59eb7bf9a499da55046760aaabc5c] backend.apps.network.utils /Users/jamesge/GitHubProjects/bk-bcs-saas/bcs-app/backend/apps/network/utils.py 339 <module> 63242 4772154880 
 	 Load extension failed: No module named 'backend.apps.network.utils_ext' 

DEBUG [2021-06-29 11:10:45] [583fe7808a5e4701bc0a7674de3493ac] backend.bcs_k8s.app.repo /Users/jamesge/GitHubProjects/bk-bcs-saas/bcs-app/backend/bcs_k8s/app/repo.py 48 <module> 63242 4772154880 
 	 Load extension failed: No module named 'backend.bcs_k8s.app.repo_ext' 

ERROR [2021-06-29 11:10:45] [a189342b9961496bb72d935bdbc92438] backend.utils.requests /Users/jamesge/GitHubProjects/bk-bcs-saas/bcs-app/backend/utils/requests.py 61 _request 63242 4772154880 
 	 第三方请求异常，url: /apigw/managementapi/get_api_public_key/, Invalid URL '/apigw/managementapi/get_api_public_key/': No schema supplied. Perhaps you meant http:///apigw/managementapi/get_api_public_key/? 
Traceback (most recent call last):
  File "/Users/jamesge/GitHubProjects/bk-bcs-saas/bcs-app/backend/bcs_web/constants.py", line 25, in <module>
    BCS_APP_APIGW_PUBLIC_KEY = getattr(settings, 'BCS_APP_APIGW_PUBLIC_KEY')
  File "/Users/jamesge/.local/share/virtualenvs/paas-web-backend-ce-js1Hoyit/lib/python3.6/site-packages/django/conf/__init__.py", line 57, in __getattr__
    val = getattr(self._wrapped, name)
AttributeError: 'Settings' object has no attribute 'BCS_APP_APIGW_PUBLIC_KEY'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jamesge/GitHubProjects/bk-bcs-saas/bcs-app/backend/utils/requests.py", line 52, in _request
    resp = rpool.request(method, url, params=params, data=data, json=json, headers=headers, **kwargs)
  File "/Users/jamesge/.local/share/virtualenvs/paas-web-backend-ce-js1Hoyit/lib/python3.6/site-packages/requests/sessions.py", line 519, in request
    prep = self.prepare_request(req)
  File "/Users/jamesge/.local/share/virtualenvs/paas-web-backend-ce-js1Hoyit/lib/python3.6/site-packages/requests/sessions.py", line 462, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/Users/jamesge/.local/share/virtualenvs/paas-web-backend-ce-js1Hoyit/lib/python3.6/site-packages/requests/models.py", line 313, in prepare
    self.prepare_url(url, params)
  File "/Users/jamesge/.local/share/virtualenvs/paas-web-backend-ce-js1Hoyit/lib/python3.6/site-packages/requests/models.py", line 387, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '/apigw/managementapi/get_api_public_key/': No schema supplied. Perhaps you meant http:///apigw/managementapi/get_api_public_key/?
ERROR [2021-06-29 11:10:45] [5bfc675a1699467c811a499b52de7800] backend.components.apigw /Users/jamesge/GitHubProjects/bk-bcs-saas/bcs-app/backend/components/apigw.py 31 get_api_public_key 63242 4772154880 
 	 get api public key failed: 第三方请求失败，Invalid URL '/apigw/managementapi/get_api_public_key/': No schema supplied. Perhaps you meant http:///apigw/managementapi/get_api_public_key/? 
Traceback (most recent call last):
  File "/Users/jamesge/GitHubProjects/bk-bcs-saas/bcs-app/backend/bcs_web/constants.py", line 25, in <module>
    BCS_APP_APIGW_PUBLIC_KEY = getattr(settings, 'BCS_APP_APIGW_PUBLIC_KEY')
  File "/Users/jamesge/.local/share/virtualenvs/paas-web-backend-ce-js1Hoyit/lib/python3.6/site-packages/django/conf/__init__.py", line 57, in __getattr__
    val = getattr(self._wrapped, name)
AttributeError: 'Settings' object has no attribute 'BCS_APP_APIGW_PUBLIC_KEY'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jamesge/GitHubProjects/bk-bcs-saas/bcs-app/backend/utils/requests.py", line 52, in _request
    resp = rpool.request(method, url, params=params, data=data, json=json, headers=headers, **kwargs)
  File "/Users/jamesge/.local/share/virtualenvs/paas-web-backend-ce-js1Hoyit/lib/python3.6/site-packages/requests/sessions.py", line 519, in request
    prep = self.prepare_request(req)
  File "/Users/jamesge/.local/share/virtualenvs/paas-web-backend-ce-js1Hoyit/lib/python3.6/site-packages/requests/sessions.py", line 462, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/Users/jamesge/.local/share/virtualenvs/paas-web-backend-ce-js1Hoyit/lib/python3.6/site-packages/requests/models.py", line 313, in prepare
    self.prepare_url(url, params)
  File "/Users/jamesge/.local/share/virtualenvs/paas-web-backend-ce-js1Hoyit/lib/python3.6/site-packages/requests/models.py", line 387, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '/apigw/managementapi/get_api_public_key/': No schema supplied. Perhaps you meant http:///apigw/managementapi/get_api_public_key/?

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jamesge/GitHubProjects/bk-bcs-saas/bcs-app/backend/components/apigw.py", line 28, in get_api_public_key
    data = requests.bk_get(url, params=params, headers=headers)
  File "/Users/jamesge/GitHubProjects/bk-bcs-saas/bcs-app/backend/utils/decorators.py", line 116, in _wrapped_func
    resp = func(*args, **kwargs)
  File "/Users/jamesge/GitHubProjects/bk-bcs-saas/bcs-app/backend/utils/requests.py", line 62, in _request
    raise ComponentError(err_msg or error)
backend.utils.exceptions.ComponentError: 第三方请求失败，Invalid URL '/apigw/managementapi/get_api_public_key/': No schema supplied. Perhaps you meant http:///apigw/managementapi/get_api_public_key/?
DEBUG [2021-06-29 11:10:45] [f95749d9c3574c55adaad253c0a13aa5] backend.components.bk_repo /Users/jamesge/GitHubProjects/bk-bcs-saas/bcs-app/backend/components/bk_repo.py 68 <module> 63242 4772154880 
 	 Load extension failed: No module named 'backend.components.bk_repo_ext' 

ERROR [2021-06-29 11:10:45] [417be04eb7cf4686bc481fd412eaa2af] backend.utils.requests /Users/jamesge/GitHubProjects/bk-bcs-saas/bcs-app/backend/utils/requests.py 61 _request 63242 4772154880 
 	 第三方请求异常，url: /apigw/managementapi/get_api_public_key/, Invalid URL '/apigw/managementapi/get_api_public_key/': No schema supplied. Perhaps you meant http:///apigw/managementapi/get_api_public_key/? 
Traceback (most recent call last):
  File "/Users/jamesge/GitHubProjects/bk-bcs-saas/bcs-app/backend/utils/requests.py", line 52, in _request
    resp = rpool.request(method, url, params=params, data=data, json=json, headers=headers, **kwargs)
  File "/Users/jamesge/.local/share/virtualenvs/paas-web-backend-ce-js1Hoyit/lib/python3.6/site-packages/requests/sessions.py", line 519, in request
    prep = self.prepare_request(req)
  File "/Users/jamesge/.local/share/virtualenvs/paas-web-backend-ce-js1Hoyit/lib/python3.6/site-packages/requests/sessions.py", line 462, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/Users/jamesge/.local/share/virtualenvs/paas-web-backend-ce-js1Hoyit/lib/python3.6/site-packages/requests/models.py", line 313, in prepare
    self.prepare_url(url, params)
  File "/Users/jamesge/.local/share/virtualenvs/paas-web-backend-ce-js1Hoyit/lib/python3.6/site-packages/requests/models.py", line 387, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '/apigw/managementapi/get_api_public_key/': No schema supplied. Perhaps you meant http:///apigw/managementapi/get_api_public_key/?
ERROR [2021-06-29 11:10:45] [230cb3bba99f4628b791e6d142a7b98a] backend.components.apigw /Users/jamesge/GitHubProjects/bk-bcs-saas/bcs-app/backend/components/apigw.py 31 get_api_public_key 63242 4772154880 
 	 get api public key failed: 第三方请求失败，Invalid URL '/apigw/managementapi/get_api_public_key/': No schema supplied. Perhaps you meant http:///apigw/managementapi/get_api_public_key/? 
Traceback (most recent call last):
  File "/Users/jamesge/GitHubProjects/bk-bcs-saas/bcs-app/backend/utils/requests.py", line 52, in _request
    resp = rpool.request(method, url, params=params, data=data, json=json, headers=headers, **kwargs)
  File "/Users/jamesge/.local/share/virtualenvs/paas-web-backend-ce-js1Hoyit/lib/python3.6/site-packages/requests/sessions.py", line 519, in request
    prep = self.prepare_request(req)
  File "/Users/jamesge/.local/share/virtualenvs/paas-web-backend-ce-js1Hoyit/lib/python3.6/site-packages/requests/sessions.py", line 462, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/Users/jamesge/.local/share/virtualenvs/paas-web-backend-ce-js1Hoyit/lib/python3.6/site-packages/requests/models.py", line 313, in prepare
    self.prepare_url(url, params)
  File "/Users/jamesge/.local/share/virtualenvs/paas-web-backend-ce-js1Hoyit/lib/python3.6/site-packages/requests/models.py", line 387, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '/apigw/managementapi/get_api_public_key/': No schema supplied. Perhaps you meant http:///apigw/managementapi/get_api_public_key/?

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jamesge/GitHubProjects/bk-bcs-saas/bcs-app/backend/components/apigw.py", line 28, in get_api_public_key
    data = requests.bk_get(url, params=params, headers=headers)
  File "/Users/jamesge/GitHubProjects/bk-bcs-saas/bcs-app/backend/utils/decorators.py", line 116, in _wrapped_func
    resp = func(*args, **kwargs)
  File "/Users/jamesge/GitHubProjects/bk-bcs-saas/bcs-app/backend/utils/requests.py", line 62, in _request
    raise ComponentError(err_msg or error)
backend.utils.exceptions.ComponentError: 第三方请求失败，Invalid URL '/apigw/managementapi/get_api_public_key/': No schema supplied. Perhaps you meant http:///apigw/managementapi/get_api_public_key/?
DEBUG [2021-06-29 11:10:45] [7404b0b83dba455c84f82899a6c821bc] backend.apps.apis.constants /Users/jamesge/GitHubProjects/bk-bcs-saas/bcs-app/backend/apps/apis/constants.py 40 <module> 63242 4772154880 
 	 Load extension failed: No module named 'backend.apps.apis.constants_ext' 

ERROR [2021-06-29 11:10:45] [69a847274ff2412a8f340e771177cafc] backend.utils.requests /Users/jamesge/GitHubProjects/bk-bcs-saas/bcs-app/backend/utils/requests.py 61 _request 63242 4772154880 
 	 第三方请求异常，url: /apigw/managementapi/get_api_public_key/, Invalid URL '/apigw/managementapi/get_api_public_key/': No schema supplied. Perhaps you meant http:///apigw/managementapi/get_api_public_key/? 
Traceback (most recent call last):
  File "/Users/jamesge/GitHubProjects/bk-bcs-saas/bcs-app/backend/apis/constants.py", line 25, in <module>
    BCS_APP_APIGW_PUBLIC_KEY = getattr(settings, 'BCS_APP_APIGW_PUBLIC_KEY')
  File "/Users/jamesge/.local/share/virtualenvs/paas-web-backend-ce-js1Hoyit/lib/python3.6/site-packages/django/conf/__init__.py", line 57, in __getattr__
    val = getattr(self._wrapped, name)
AttributeError: 'Settings' object has no attribute 'BCS_APP_APIGW_PUBLIC_KEY'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jamesge/GitHubProjects/bk-bcs-saas/bcs-app/backend/utils/requests.py", line 52, in _request
    resp = rpool.request(method, url, params=params, data=data, json=json, headers=headers, **kwargs)
  File "/Users/jamesge/.local/share/virtualenvs/paas-web-backend-ce-js1Hoyit/lib/python3.6/site-packages/requests/sessions.py", line 519, in request
    prep = self.prepare_request(req)
  File "/Users/jamesge/.local/share/virtualenvs/paas-web-backend-ce-js1Hoyit/lib/python3.6/site-packages/requests/sessions.py", line 462, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/Users/jamesge/.local/share/virtualenvs/paas-web-backend-ce-js1Hoyit/lib/python3.6/site-packages/requests/models.py", line 313, in prepare
    self.prepare_url(url, params)
  File "/Users/jamesge/.local/share/virtualenvs/paas-web-backend-ce-js1Hoyit/lib/python3.6/site-packages/requests/models.py", line 387, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '/apigw/managementapi/get_api_public_key/': No schema supplied. Perhaps you meant http:///apigw/managementapi/get_api_public_key/?
ERROR [2021-06-29 11:10:45] [3dddf28b3cd04d9cad23edfffa05569f] backend.components.apigw /Users/jamesge/GitHubProjects/bk-bcs-saas/bcs-app/backend/components/apigw.py 31 get_api_public_key 63242 4772154880 
 	 get api public key failed: 第三方请求失败，Invalid URL '/apigw/managementapi/get_api_public_key/': No schema supplied. Perhaps you meant http:///apigw/managementapi/get_api_public_key/? 
Traceback (most recent call last):
  File "/Users/jamesge/GitHubProjects/bk-bcs-saas/bcs-app/backend/apis/constants.py", line 25, in <module>
    BCS_APP_APIGW_PUBLIC_KEY = getattr(settings, 'BCS_APP_APIGW_PUBLIC_KEY')
  File "/Users/jamesge/.local/share/virtualenvs/paas-web-backend-ce-js1Hoyit/lib/python3.6/site-packages/django/conf/__init__.py", line 57, in __getattr__
    val = getattr(self._wrapped, name)
AttributeError: 'Settings' object has no attribute 'BCS_APP_APIGW_PUBLIC_KEY'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jamesge/GitHubProjects/bk-bcs-saas/bcs-app/backend/utils/requests.py", line 52, in _request
    resp = rpool.request(method, url, params=params, data=data, json=json, headers=headers, **kwargs)
  File "/Users/jamesge/.local/share/virtualenvs/paas-web-backend-ce-js1Hoyit/lib/python3.6/site-packages/requests/sessions.py", line 519, in request
    prep = self.prepare_request(req)
  File "/Users/jamesge/.local/share/virtualenvs/paas-web-backend-ce-js1Hoyit/lib/python3.6/site-packages/requests/sessions.py", line 462, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/Users/jamesge/.local/share/virtualenvs/paas-web-backend-ce-js1Hoyit/lib/python3.6/site-packages/requests/models.py", line 313, in prepare
    self.prepare_url(url, params)
  File "/Users/jamesge/.local/share/virtualenvs/paas-web-backend-ce-js1Hoyit/lib/python3.6/site-packages/requests/models.py", line 387, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '/apigw/managementapi/get_api_public_key/': No schema supplied. Perhaps you meant http:///apigw/managementapi/get_api_public_key/?

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jamesge/GitHubProjects/bk-bcs-saas/bcs-app/backend/components/apigw.py", line 28, in get_api_public_key
    data = requests.bk_get(url, params=params, headers=headers)
  File "/Users/jamesge/GitHubProjects/bk-bcs-saas/bcs-app/backend/utils/decorators.py", line 116, in _wrapped_func
    resp = func(*args, **kwargs)
  File "/Users/jamesge/GitHubProjects/bk-bcs-saas/bcs-app/backend/utils/requests.py", line 62, in _request
    raise ComponentError(err_msg or error)
backend.utils.exceptions.ComponentError: 第三方请求失败，Invalid URL '/apigw/managementapi/get_api_public_key/': No schema supplied. Perhaps you meant http:///apigw/managementapi/get_api_public_key/?
